Split directory layouts for image-based install.
From: Lassi Tuura <lat@cern.ch>


git-svn-id: svn+ssh://svn.cern.ch/reps/CMSDMWM/Infrastructure/branches/deployment-reorg@11677 4525493e-7705-40b1-a816-d608a930855b

diff --git a/Deploy b/Deploy
--- a/Deploy
+++ b/Deploy
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-##H Deploy [-v] ROOT [SERVICE...]
+##H Deploy [OPTIONS] ROOT [SERVICE...]
 ##H
 ##H Deploy one or more SERVICEs into the ROOT directory.
 ##H
@@ -8,20 +8,22 @@
 ##H  -M             Activate $MIGRATION commands.
 ##H  -a             Activate production installation under multiple accounts.
 ##H  -r A=B         Use repository B instead of A (e.g. comp=comp.pre).
-##H  -C ROOT DIR    SVN check out configuration from ROOT/[TAG]/DIR.
-##H  -t TAG         SVN check out configuration from using TAG (e.g. tags/foo).
-##H  -d SCRIPT-DIR  Look for service installation scripts in SCRIPT-DIR.
+##H  -t VERSION     Install software as VERSION.
+##H  -p AUTH-DIR    Use private secrets from AUTH-DIR (default: use dummies).
+##H  -s STAGES      Install only STAGES parts of recipes (prep sw post).
+##H  -H HOST        Install as if for HOST (default: hostname).
 ##H  -h             Display this help.
 ##H
 ##H Remaining parameters are installation root directory ROOT and list
-##H of service names to install.  Assuming you want to install WMFoo to
-##H $PWD/test, with dependent package WMBar, have DeployWMFoo in $PWD
-##H and DeployWMBar in $PWD/extra, and you want to install using HEAD
-##H of SITECONF and pre-release RPMs with standard multi-account set-up,
-##H call Deploy as follows:
+##H of service names to install. Per-service deployment recipes and
+##H configuration are taken from the same directory as this script.
 ##H
-##H     ./Deploy -a -r comp=comp.pre -t HEAD -d $PWD/extra $PWD/test WMFoo
+##H Example to install service 'foo' into /data as version hg1103-backend
+##H from pre-release repository, using official secrets from 'secrets'.
 ##H
+##H   scp -rp cmsweb@lxplus.cern.ch:private/conf secrets
+##H   svn co svn+ssh://svn.cern.ch/reps/Infrastructure/trunk/Deployment d
+##H   d/Deploy -a -r comp=comp.pre -V hg1103a-backend -A secrets /data foo
 
 MIGRATION=
 
@@ -29,12 +31,11 @@ repoedit=n
 arch=slc5_amd64_gcc434
 now=$(date +%Y%m%d%H%M%S)
 host=$(hostname -s)
-stages="prep sw post"
+stages="prep sw"
 nogroups=true
-servicedirs="$(cd $(dirname $0) && pwd) $PWD"
-cfgroot=http://svnweb.cern.ch/guest/CMSDMWM/Infrastructure
-cfgsubdir=Deployment
-cfgtag=tags/CMSWEB_CONFIG_PROD
+servicedir="$(cd $(dirname $0) && pwd)"
+cfgversion=
+privauthdir=
 
 while [ $# -ge 1 ]; do
   case $1 in
@@ -42,9 +43,9 @@ while [ $# -ge 1 ]; do
     -a ) nogroups=false; shift ;;
     -r ) repoedit="s/${2%=*}/${2#*=}/; $repoedit"; shift; shift ;;
     -s ) stages="$2"; shift; shift ;;
-    -C ) cfgroot="$2" cfgsubdir="$3"; shift; shift; shift ;;
-    -t ) cfgtag="$2"; shift; shift ;;
-    -d ) servicedirs="$servicedirs $2"; shift; shift ;;
+    -t ) cfgversion="$2"; shift; shift ;;
+    -p ) privauthdir="$2"; shift; shift ;;
+    -H ) host="$2"; shift; shift ;;
     -h ) perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0 1>&2; exit 1 ;;
     -* ) echo "$0: unrecognised option $1, use -h for help" 1>&2; exit 1 ;;
     *  ) break ;;
@@ -59,29 +60,53 @@ if [ $# -lt 1 ]; then
   exit 1
 fi
 
+if [ X"$cfgversion" = X ]; then
+  echo "$0: missing software tag version (-t option)" 1>&2
+  exit 1
+fi
+
+case $cfgversion in */* | . | .. | .* )
+  echo "$0: invalid configuration version name '$cfgversion'" 1>&2
+  exit 1 ;;
+esac
+
+if [ X"$privauthdir" != X ] && [ ! -d "$privauthdir" ]; then
+  echo "$privauthdir: not a directory" 1>&2
+  exit 1
+fi
+
 # Set SCRAM_ARCH. Lots of things won't work without it being set.
 export SCRAM_ARCH=$arch
-export CVSROOT=:pserver:anonymous@cmscvs.cern.ch:/cvs/CMSSW
 
 # Make sure the installation directory exists.
 root="$1"; shift
-[ -d $root ] || {
-  mkdir -p $root || exit $?
-  chmod ug+rw,o-w $root || exit $?
-  $chgrp _sw $root || exit $?
-} || exit 2
+[ -d $root ] || mkdir -p $root || exit $?
 
-# Start error log and make sure it gets wiped on exit.
-errlog=$root/.deploy-$(date +%Y%m%d-%H%M%S)-$$.log
-trap "(exit 77); exit 77" 1 2 15
-: > $errlog
-exec 11>&1 22>&2
-exec 1>>$errlog 2>&1
-set -ex
+# Create directory for deployment logs. Must be writeable by _sw.
+[ -d $root/.deploy ] || {
+  mkdir -p $root/.deploy || exit $?
+  $chmod ug+rw,o-w $root/.deploy || exit $?
+  $chgrp _sw $root/.deploy || exit $?
+}
 
-# Record beginning of installation.
-note() { echo "$*" >> $errlog; echo "$*" 1>&11; }
-note "INFO: $now: starting deployment of: $*"
+# Create directory for the configuration version we are about to create.
+# (Re)set 'current' link to what we are about to install if necessary.
+for dir in $root/$cfgversion{,/bin,/apps,/auth,/config}; do
+  [ -d $dir ] || {
+    mkdir -p $dir || exit $?
+    $chmod ug+rw,o-w $dir || exit $?
+    $chgrp _sw $dir || exit $?
+  }
+done
+
+for dir in $root/{logs,state,enabled}; do
+  [ -d $dir ] || mkdir -p $dir || exit $?
+done
+
+if [ ! -L $root/current ] || [ X$(readlink $root/current) != X$cfgversion ]; then
+  rm -f $root/current || exit $?
+  ln -s $cfgversion $root/current || exit $?
+fi
 
 ######################################################################
 # Installation routines
@@ -113,20 +138,34 @@ setgroup()
 sysboot()
 {
   if $nogroups; then
-    echo "@reboot $PWD/config/manage ${2-sysboot}"
+    echo "@reboot $project_config/manage ${1-sysboot}"
   else
-    echo "@reboot sudo -H -u $1 bashs -l -c '$PWD/config/manage ${2-sysboot}'"
+    echo "@reboot sudo -H -u _$project bashs -l -c '$project_config/manage ${1-sysboot}'"
   fi
+}
+
+# Clean up crontab entries for the project
+mkcrontab()
+{
+  crontab -l | { fgrep -v -e $project_config/ || true; }
 }
 
 # Create application proxy
 mkproxy()
 {
-  local acct=$1 path=$2
+  local acct=_$project
+  local path=$PWD/proxy/proxy.cert
   local link=$(echo $path | md5sum | awk '{print $1}' | cut -b 1-8)
-  local pxfile=$root/projects/conf/certs/PX$link
+  local pxfile=$root/current/auth/proxy/PX$link
+  local pxdir=$root/current/auth/proxy
+
+  mkdir -p $pxdir
+  setgroup u+rwx,g+rx,o-rwx _config $pxdir
+
   echo "$acct $path" > $pxfile
-  setgroup u+rw,go-rwx,g+r _config $pxfile
+  setgroup u+rw,go-rwx _config $pxfile
+
+  mkdir -p $PWD/proxy
   setgroup ug+rwx,o-rwx $acct $(dirname $path)
 }
 
@@ -134,22 +173,35 @@ mkproxy()
 # With groups enabled the project directory is writable by _sw.
 mkproj()
 {
-  local name=$1
-  local dir=
-  shift
-
-  mkdir -p $root/projects/$name
-  $chgrp _sw $root/projects/$name
-  $chmod ug+rw,o-w $root/projects/$name
-
-  for dir; do
-   case $dir in
-     /*) mkdir -p $dir ;;
-     * ) mkdir -p $root/projects/$name/$dir ;;
-   esac
+  local nolog=false
+  local nostate=false
+  while [ $# -ge 1 ]; do
+    case $1 in
+      -s ) nostate=true; shift ;;
+      -l ) nolog=true; shift ;;
+      -* ) echo "$0: mkproj: unexpected option $1" 1>&2; exit 1;;
+      *  ) break ;;
+    esac
   done
 
-  cd $root/projects/$name
+  mkdir -p $project_config
+  $chgrp _sw $project_config
+  $chmod ug+rw,o-w $project_config
+
+  if $nolog; then :; else
+    mkdir -p $project_logs
+    setgroup ug+rw,o-w _$project $project_logs
+  fi
+
+  if $nostate; then :; else
+    mkdir -p $project_state
+    setgroup ug+rw,o-w _$project $project_state
+    cd $project_state
+    for dir; do
+      mkdir -p $dir
+      setgroup ug+rw,o-w _$project $dir
+    done
+  fi
 }
 
 # Source software management environment for a repository.
@@ -157,12 +209,12 @@ mkproj()
 inrepo()
 {
   local repo=$1
-  local inpath=${2-$repo}
-  if [ ! -f $root/${inpath}sw/.bootstrapped ]; then
-    note "INFO: bootstrapping $repo software area in $root/${inpath}sw"
-    if (rm -fr $root/${inpath}sw
-        mkdir -p $root/${inpath}sw
-        cd $root/${inpath}sw
+  local swarea=$2
+  if [ ! -f $swarea/.bootstrapped ]; then
+    note "INFO: bootstrapping $repo software area in $swarea"
+    if (rm -fr $swarea
+        mkdir -p $swarea
+        cd $swarea
         wget -q http://cmsrep.cern.ch/cmssw/${repo%.*}/bootstrap.sh
         sh -x ./bootstrap.sh -architecture $arch -path $PWD -repository $repo \
           setup > $PWD/bootstrap-$arch.log 2>&1
@@ -173,38 +225,40 @@ inrepo()
       exit 3
     fi
   fi
-  . $root/${inpath}sw/$arch/external/apt/*/etc/profile.d/init.sh
+  . $swarea/$arch/external/apt/*/etc/profile.d/init.sh
 }
 
 # Deploy some component.
 deploy()
 {
-  local found=false
   local name=$(echo $1 | tr - _)
   eval local did="\$${name}_deployed"
   if [ X$did = X ]; then
-    local dir
-    for dir in $servicedirs; do
-      if [ -f $dir/$1/deploy ]; then
-	eval "deploy_${name}_deps() { true; }"
-	eval "deploy_${name}_prep() { true; }"
-	eval "deploy_${name}_sw() { true; }"
-	eval "deploy_${name}_post() { true; }"
-        . $dir/$1/deploy
-	found=true
-        break
-      fi
-    done
-
-    if $found; then :; else
-      note "ERROR: don't know how to deploy $1 - missing $1/deploy in $servicedirs?"
+    if [ -f $servicedir/$1/deploy ]; then
+      eval "deploy_${name}_deps() { true; }"
+      eval "deploy_${name}_prep() { true; }"
+      eval "deploy_${name}_sw() { true; }"
+      eval "deploy_${name}_post() { enable; }"
+      eval "deploy_${name}_auth() { true; }"
+      . $servicedir/$1/deploy
+    else
+      note "ERROR: cannot deploy $1, no $servicedir/$1/deploy"
       exit 4
     fi
 
-    eval deploy_${name}_deps
+    local setup=:
+    setup="$setup; project='$1'"
+    setup="$setup; project_config_src='$servicedir/$1'"
+    setup="$setup; project_config='$root/current/config/$1'"
+    setup="$setup; project_auth='$root/current/auth/$1'"
+    setup="$setup; project_state='$root/state/$1'"
+    setup="$setup; project_logs='$root/logs/$1'"
+    setup="$setup; cd \$root; [ ! -d \$project_state ] || cd \$project_state"
+
+    eval "$setup; deploy_${name}_deps"
     note "INFO: deploying $1"
     for stage in $stages; do
-      eval deploy_${name}_$stage
+      eval "$setup; deploy_${name}_$stage"
     done
     eval "${name}_deployed=1"
   else
@@ -214,65 +268,107 @@ deploy()
 
 deploy_pkg()
 {
-  local nofakes=true
+  local authfiles=
+  local authfile=
   local link=
-  local cfg=
   while [ $# -ge 1 ]; do
     case $1 in
-      -f ) nofakes=false; shift ;;
-      -l ) link=$2; shift; shift ;;
-      -c ) cfg=$2; shift; shift ;;
-      -d ) cd $root/projects/$2; shift; shift ;;
+      -a ) authfiles="$authfiles $2"; shift; shift ;;
+      -l ) link="$2"; shift; shift ;;
       -* ) echo "$0: deploy_pkg: unexpected option $1" 1>&2; exit 1;;
       *  ) break ;;
     esac
   done
 
-  local repo=$(echo $1 | sed -e "$repoedit")
-  local pkg=$2
-  local ver=$3
+  if [ $# = 0 ]; then :; else
+    local repo=$(echo $1 | sed -e "$repoedit")
+    local label=$(echo $repo | sed 's/^comp//; s/^\([^.]\)/.\1/; s/^/sw/; n')
+    local swarea=$root/$cfgversion/$label
+    local pkg=$2
+    local ver=$3
 
-  (inrepo $repo
-   apt-get update
-   { $nofakes || apt-get -y install $(apt-cache pkgnames | grep fake); }
-   apt-get -y install $pkg+$ver)
+    (inrepo $repo $swarea
+     apt-get update
+     apt-get -y install $(apt-cache pkgnames | grep fake)
+     apt-get -y install $pkg+$ver)
 
-  # Fix privs dropped by apt/rpm
-  setgroup ug+rw,o-w _sw $root/${repo}sw
-  if $nogroups; then :; else
-    BADFILES=$(find $root/${repo}sw/$arch -type f ! -group _sw -print)
-    [ X"$BADFILES" = X ] || note "WARNING: removing $BADFILES"
-    find $root/${repo}sw/$arch -type f ! -group _sw -print0 | xargs -r -t -0 rm -f
-    find $root/${repo}sw/$arch ! -type l -perm -2 -print0 | xargs -r -t -0 chmod o-w
-    find $root/${repo}sw/$arch -type d ! -perm -660 -print0 | xargs -r -t -0 chmod ug+rw
-    find $root/${repo}sw/$arch -type f ! -group _sw -print0 | xargs -r -t -0 chgrp _sw
-  fi
-
-  if [ X"$link" = X ]; then :; else
-    mkdir -p $(dirname $link)
-    rm -f $link
-    ln -s $root/${repo}sw/$arch/$(echo $pkg | tr + /)/$ver $link
-  fi
-  if [ X"$cfg" = X ]; then :; else
-    if [ -d config ]; then
-      BADFILES=$(find config -type f ! -group _config -print)
-      [ X"$BADFILES" = X ] || $nogroups || note "WARNING: removing $BADFILES"
-      $nogroups || find config -type f ! -group _config -print0 | xargs -r -t -0 rm -f
-    else
-      :
+    # Fix privs dropped by apt/rpm
+    setgroup ug+rw,o-w _sw $swarea
+    if $nogroups; then :; else
+      BADFILES=$(find $swarea/$arch -type f ! -group _sw -print)
+      [ X"$BADFILES" = X ] || note "WARNING: removing $BADFILES"
+      find $swarea/$arch -type f ! -group _sw -print0 | xargs -r -t -0 rm -f
+      find $swarea/$arch ! -type l -perm -2 -print0 | xargs -r -t -0 chmod o-w
+      find $swarea/$arch -type d ! -perm -660 -print0 | xargs -r -t -0 chmod ug+rw
+      find $swarea/$arch -type f ! -group _sw -print0 | xargs -r -t -0 chgrp _sw
     fi
-    svn -q co $cfg $cfgroot/$cfgtag/$cfgsubdir config
-    setgroup -R ug+r,go-w _config config
+
+    # Create application link.
+    [ X"$link" != X ] || link=${pkg#*+}
+    rm -f $root/current/apps/$link
+    ln -s ../$label/$arch/$(echo $pkg+$ver | tr + /) $root/current/apps/$link
   fi
+
+  # Install configuration.
+  if $nogroups; then :; else
+    BADFILES=$(find $project_config -type f ! -group _config -print)
+    [ X"$BADFILES" = X ] || note "WARNING: removing $BADFILES"
+    find $project_config -type f ! -group _config -print0 | xargs -r -t -0 rm -f
+  fi
+
+  (cd $project_config_src; find . -type f -print0 |
+   tar --null -T /dev/stdin -cf -) | tar -C $project_config -xvvf - \
+     --no-anchored --exclude CVS --exclude .svn --exclude .git \
+     --exclude '*~' --exclude '.#*' --exclude '*.swp'
+  setgroup ug+r,go-w _config $(find $project_config -type f)
+
+  # Install authentication file if any.
+  for authfile in $authfiles; do
+    local authname=$(echo $project | tr - _)
+    local authsrc=
+    local authdest=
+    case $authfile in
+      *:* ) authsrc=${authfile#*:} authdest=${authfile%*:} ;;
+      *   ) authsrc=$authfile authdest=$(basename $authfile) ;;
+    esac
+
+    mkdir -p $project_auth
+    if [ X"$privauthdir" = X ] || [ ! -f $privauthdir/$authsrc ]; then
+      if [ -f $project_auth/$authdest ]; then :; else
+        eval "deploy_${authname}_auth $authsrc" > $project_auth/$authdest
+      fi
+    else
+      rm -f $project_auth/$authdest
+      cp $privauthdir/$authsrc $project_auth/$authdest
+    fi
+
+    setgroup u=rwx,g=rx,o-rwx _config $(find $project_auth -type d)
+    setgroup ug=r,o-rwx _config $(find $project_auth -type f)
+  done
 }
 
+# Enable or disable server on a particular node.
+enable() { touch $root/enabled/$project; }
+disable() { rm -f $root/enabled/$project; }
+
+note() { echo "$*" >> $errlog; echo "$*" 1>&11; }
 
 ######################################################################
+# Start error log and make sure it gets wiped on exit.
+errlog=$root/.deploy/$(date +%Y%m%d-%H%M%S)-$$.log
+trap "(exit 77); exit 77" 1 2 15
+: > $errlog
+exec 11>&1 22>&2
+exec 1>>$errlog 2>&1
+set -ex
+
+# Record beginning of installation.
+note "INFO: $now: starting deployment of: $*"
+
 # Loop over all requested services and install them one at a time.
-(for svc; do
-  cd $root
-  deploy $svc
-done)
+(for svc; do deploy $svc; done)
+
+# Resume normal output.
 exit=$?
 set +ex
 exec 1>&11 2>&22
diff --git a/admin/ProxyRenew b/admin/ProxyRenew
--- a/admin/ProxyRenew
+++ b/admin/ProxyRenew
@@ -1,10 +1,10 @@
 #!/bin/sh
 
-### ProxyRenew CERT-DIRECTORY LABEL VOMS[:/GROUP/Role=ROLE]
+### ProxyRenew CERT-DIRECTORY PROXY-DIRECTORY LABEL VOMS[:/GROUP/Role=ROLE]
 ###
 ### Given 'hostcert.pem' and 'hostkey.pem' in CERT-DIRECTORY, maintains
 ### one or more proxy certificates, 'proxy-<LOGIN>.cert' and 'proxy.cert',
-### in the same directory.  The proxy is renewed by attempting to acquire
+### in PROXY-DIRECTORY.  The proxy is renewed by attempting to acquire
 ### new delegations titled LABEL_<LOGIN> for every seed proxy <LOGIN>,
 ### extended with voms attribute VOMS (VOMS:/GROUP/Role=ROLE if required).
 ### Warns the operators if none of the available proxies can be renewed or
@@ -12,7 +12,7 @@
 ###
 ### The proxy would normally be renewed using a cron job like this:
 ###
-###  3 */3 * * * /data/projects/admin/ProxyRenew /data/projects/conf/certs cmsweb_backends cms
+###  3 */3 * * * /data/projects/admin/ProxyRenew /data/certs /data/current/auth/proxy cmsweb_backends cms
 ###
 ### Periodically, usually once a month, the operator should upload his or
 ### her personal proxy to myproxy.cern.ch using the following command. Do
@@ -42,21 +42,21 @@ if [ X"$1" = X-v ]; then
   shift
 fi
 
-if [ $# -ne 3 ]; then
-  echo "usage: $0 CERT-DIRECTORY LABEL VOMS[:/GROUP/Role=ROLE]" 1>&2
+if [ $# -ne 4 ]; then
+  echo "usage: $0 CERT-DIRECTORY PROXY-DIRECTORY LABEL VOMS[:/GROUP/Role=ROLE]" 1>&2
   exit 1
 fi
 
-dir="$1"
-label="$2"
-voms="$3"
+certdir="$1"
+dir="$2"
+label="$3"
+voms="$4"
 
-[ -d "$dir" ] ||
-  { echo "$dir: no such certificate directory" 1>&2; exit 2; }
-cd "$dir" ||
-  { echo "$dir: cannot change to directory" 1>&2; exit 3; }
-[ -f hostcert.pem -a -f hostkey.pem ] ||
-  { echo "$dir: no hostcert.pem/hostkey.pem/proxy.cert here" 1>&2; exit 4; }
+[ -d "$certdir" ] || { echo "$certdir: no such certificate directory" 1>&2; exit 2; }
+[ -d "$dir" ] || { echo "$dir: no such proxy directory" 1>&2; exit 1; }
+cd "$dir" || { echo "$dir: cannot change to directory" 1>&2; exit 3; }
+[ -f $certdir/hostcert.pem -a -f $certdir/hostkey.pem ] ||
+  { echo "$certdir: no hostcert.pem/hostkey.pem here" 1>&2; exit 4; }
 
 unset MYPROXY_SERVER
 unset MYPROXY_SERVER_DN
@@ -92,8 +92,8 @@ got_proxy=0 best_proxy= good_proxy= ok_proxy=
 for proxy in proxy-*.cert; do
   [ -f "$proxy" ] || continue
   login=$(echo "$proxy" | sed 's/^proxy-//; s/\.cert//')
-  export X509_USER_CERT=$PWD/hostcert.pem
-  export X509_USER_KEY=$PWD/hostkey.pem
+  export X509_USER_CERT=$certdir/hostcert.pem
+  export X509_USER_KEY=$certdir/hostkey.pem
   unset X509_USER_PROXY
 
   # Check the proxy is valid at all. If not, complain and delete it
diff --git a/overview/manage b/overview/manage
--- a/overview/manage
+++ b/overview/manage
@@ -1,142 +1,115 @@
-#!/bin/zsh
-setopt sh_word_split
+#! /bin/bash
 
 case $(id -un) in cmsweb ) echo "ERROR: please use another account" 1>&2; exit 1;; esac
 
-# Overview management command. Intended to run at server boot, for example
-# via '@reboot /data/overview/config/manage restart' crontab entry, and
-# after a server upgrade. If server processes are already running, they
-# are first stopped.
-#
-# See the operations documentation on how to use this script:
-# https://twiki.cern.ch/twiki/bin/view/CMS/OverviewDeployment
+# Overview management script
 
-######################################################################
-# Set parameters. Use the latest installed server by default.
-#
-# Collect arguments and verify the invocation came from documented
-# (copy-and-paste) instructions to avoid ops mishaps, such as one
-# caused tired or insufficiently cafeinated operator.
-#
-# Note that we treat "start" and "restart" actions identically to
-# prevent operational errors of starting overlapping servers.
-PS4="+ "
-ACT=${1:-none}
-NOW=$(date +%Y%m%d%H%M%S)
-CHECK=$(echo "$2" | md5sum | awk '{print $1}')
-HOST=$(hostname | tr '[:upper:]' '[:lower:]' | sed 's/\..*//')
-OV_DIR=$(dirname $(dirname $0))
+ME=$(basename $(dirname $0))
+TOP=$(cd $(dirname $0)/../../.. && pwd)
+ROOT=$(cd $(dirname $0)/../.. && pwd)
+CFGDIR=$(dirname $0)
+LOGDIR=$TOP/logs/$ME
+STATEDIR=$TOP/state/$ME
+SERVICE_TITLE="Overview"
+TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/OverviewDeployment#Other_server_operation"
+CFGFILE=$CFGDIR/server-conf.py
+. $ROOT/apps/overview/etc/profile.d/env.sh
+export OVERVIEW_ROOT
 
-case $HOST in
-  vocms106 | vocms107 | vocms50 | vocms53 | vocms51 | vocms109 )
-    CONF=server-conf.py ;;
-  * )
-    CONF=dev-conf.py ;;
-esac
-
-EXTRA=
-case $ACT in *=* ) EXTRA=${ACT#*\=} ACT=${ACT%\=*} ;; esac
-case $ACT in stop | status | restart | sysboot ) ;; start ) ACT=restart ;; * )
-  echo "$0: unrecognised action '${ACT:-(none)}' (arg: $1);" \
-       "please check documentation." 1>&2
-  exit 1 ;;
-esac
-
-if [ -n "$(echo "$EXTRA" | sed -e 's/,*webserver,*//g' -e 's/,*logger,*//g')" ]; then
-  echo "$0: unrecognised action parameter '${EXTRA:-(none)}';" \
-       "please check documentation." 1>&2
-  exit 1
-fi
-
-[ $ACT = status ] ||
-{ ps -oargs= $PPID | grep -q -e crond; } ||
-[ X"$CHECK" = X94e261a5a70785552d34a65068819993 ] ||
-{ echo "$0: cannot complete operation, please check documentation."; exit 2; }
-
-######################################################################
-# Utilities.
-refuseproc() {
-  local title="$1" pat="$2" reason="$3"
-  if [ $(pgrep -u $(id -u) -f "$pat" | wc -l) != 0 ]; then
-    echo "$title: $reason because processes matching '$pat' are still running" 1>&2
-    exit 4
+# Function to start the service conditionally on crond restart
+function sysboot {
+  if [ $(pgrep -u $(id -u) -f "[/]ovGui $CFGFILE" | wc -l) = 0 ]; then
+    start
   fi
 }
 
-statproc() {
-  local title="$1" pat="$2"
-  echo "${newline}${title}:"
-  pgrep -u $(id -u) -f "$pat" | xargs -r ps -o pid=,bsdstart=,args= |
-    perl -p -e 's/^/  /; END { $. || print "  (none running)\n"; }'
-  newline="\n"
+# Function to start the service
+function start {
+  cd $STATEDIR
+  ovControl start all from $CFGFILE
 }
 
-killproc() {
-  local T title pat nextmsg
-  T=1 title="$1" pat="$2"
-  nextmsg="${newline}Stopping ${title}:"
-  for pid in $(pgrep -u $(id -u) -f "$pat" | sort -rn); do
-    psline=$(ps -o pid=,bsdstart=,args= $pid |
-             perl -n -e 'print join(" ", (split)[0..4])')
-    [ -n "$nextmsg" ] && { echo "$nextmsg"; nextmsg=; }
-    echo -n "Stopping $pid ($psline):"
-    for sig in TERM TERM QUIT KILL; do
-      echo -n " SIG$sig"
-      kill -$sig $pid
-      sleep 1
-      [ $(ps h $pid | wc -l) = 0 ] && break
-      sleep $T
-      T=$(expr $T \* 2)
-      [ $(ps h $pid | wc -l) = 0 ] && break
-    done
-    echo
-    newline="\n"
-  done
+# Function to stop the service
+function stop {
+  ovControl stop all from $CFGFILE
 }
 
-######################################################################
-# Source server environment. Move to $OV_DIR so cwd is safe.
-cd $OV_DIR
-. app/etc/profile.d/env.sh
+# Function to chack the status of the process
+function status {
+  PIDS=$(pgrep -u $(id -u) -f "[/]ovGui $CFGFILE")
+  if [ X"$PIDS" != X ]; then
+    echo "$SERVICE_TITLE is RUNNING, PID:" $PIDS
+  else
+    echo "$SERVICE_TITLE is NOT RUNNING."
+  fi
+}
 
-# If this is a status call, show running processes and exit now.
-newline=
-if [ $ACT = status ]; then
-  case ${EXTRA:-logger} in *logger* )
-    statproc "Loggers" "ovRotateLogs" ;;
-  esac
+#######################################################
+# Function to provide the help for the user
+# To edit the help provided, edit lines with the ##H prefix
+#######################################################
+##H Available actions:
+##H   sysboot - start server from crond if not running
+##H   status - show current service's status
+##H   start - start the service
+##H   stop - stop the service
+##H   restart - restart the service
+##H   version - get current version of the service
+##H Security string - string needed to perform actions, see twiki page
+#######################################################
+function help {
+  echo "$SERVICE_TITLE management script"
+  echo "Usage: $0 status|start|stop|restart|help|version security_string"
+  echo "For more details, check the Twiki page: $TWIKI_PAGE"
+  perl -ne '/^##H / && do { s/^##H ?//; print }' < $0
+}
 
-  case ${EXTRA:-webserver} in *webserver* )
-    statproc "Web servers" "ovGui" ;;
-  esac
+# Function to check the security string.
+function check {
+  CHECK=$(echo "$1" | md5sum | awk '{print $1}')
+  if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
+    echo "$0: cannot complete operation, please check documentation."
+    exit 2;
+  fi
+}
 
-  exit 0
-fi
+#######################################################
+# The engine of the script. The place where the
+# script reacts to the actions.
+# Params: $1 - action
+#         $2 - security string
+#######################################################
 
-# If this is sysboot, check if the server is running. If not, start.
-if [ $ACT = sysboot ]; then
-  [ $(pgrep -u $(id -u) -f "ovGui" | wc -l) = 0 ] || exit 0
-  ACT=restart
-fi
-
-# Should be stop or restart from here on.
-[ $ACT = restart ] || [ $ACT = stop ] || { echo "$0: $LINENO: internal error"; exit 3; }
-
-######################################################################
-# Stop any existing daemons.
-
-newline=
-case ${EXTRA:-webserver} in *webserver* )
-  (set -x; ovControl stop all from $OV_DIR/config/$CONF) ;;
-esac
-
-[ $ACT = stop ] && exit 0
-
-# Should be restart from here on.
-[ $ACT = restart ] || { echo "$0: $LINENO: internal error"; exit 3; }
-
-######################################################################
-# Start web server if requested.
-case ${EXTRA:-webserver} in *webserver* )
-  (set -x; ovControl start all from $OV_DIR/config/$CONF) ;;
+case $1 in
+  sysboot)
+    if ps -oargs= $PPID | grep -q -e crond; then
+      sysboot
+    else
+      echo "$0: sysboot is for cron only" 1>&2
+      exit 1
+    fi
+    ;;
+  start | restart)
+    check "$2"
+    stop
+    start
+    status
+    ;;
+  status)
+    status
+    ;;
+  stop)
+    check "$2"
+    stop
+    status
+    ;;
+  help)
+    help
+    ;;
+  version)
+    echo "Management script for $SERVICE_TITLE $T0MON_VERSION."
+    ;;
+  *)
+    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
+    exit 1 ;;
 esac
