changing lemon to collectd command (#812)

diff --git a/admin/InstallProd b/admin/InstallProd
--- a/admin/InstallProd
+++ b/admin/InstallProd
@@ -374,7 +374,7 @@ case $STAGE in
     case $WHAT in
       check )
         for host in $HOSTS; do
-          echo 'sudo /usr/sbin/lemon-host-check -t 15' | ssh cmsweb@$host bashs -l || true
+          echo 'sudo /usr/bin/collectdctl listval state=FAILURE' | ssh cmsweb@$host bashs -l || true
 	done
         echo "Checking alarm status in roger:"
         ssh -o PubkeyAuthentication=no $PXUSER@aiadm.cern.ch \
