Avoid unnecessary fixed path references and fix paths for production layout.
From: Lassi Tuura <lat@cern.ch>


git-svn-id: svn+ssh://svn.cern.ch/reps/CMSDMWM/Infrastructure/branches/deployment-reorg@11806 4525493e-7705-40b1-a816-d608a930855b

diff --git a/dqmgui/daily b/dqmgui/daily
--- a/dqmgui/daily
+++ b/dqmgui/daily
@@ -9,36 +9,34 @@
 # Figure out where the server is based on this script's location.
 ME=$(basename $(dirname $0))
 TOP=$(cd $(dirname $0)/../../.. && pwd)
-ROOT=$(cd $(dirname $0)/../.. && pwd)
-CFGDIR=$(dirname $0)
-LOGDIR=$TOP/logs/$ME
 STATEDIR=$TOP/state/$ME
-HOST=$(hostname -s | tr '[:upper:]' '[:lower:]')
 FILER=/dqmdata
-[ X"$STATEDIR" = X ] && { echo "$0: cannot figure out server location"; exit 1; }
-[ -d "$STATEDIR/sessions" ] ||
-  [ -d "$STATEDIR/offline/sessions" ] ||
-  { echo "$0: server location '$STATEDIR' is wrong"; exit 1; }
+
+if [ X"$STATEDIR" = X ]; then
+  echo "$0: cannot figure out server location"
+  exit 1
+fi
+
+if [ $(find $STATEDIR -maxdepth 2 -type d -name sessions | wc -l) = 0 ]; then
+  echo "$0: server location '$STATEDIR' is wrong"
+  exit 1
+fi
+
 mkdir $STATEDIR/.nodaily || { echo "$0: daily cannot run"; exit 1; }
 trap "rmdir $STATEDIR/.nodaily" 0 1 2 15
 
 ######################################################################
 # Purge old sessions.
-if [ -d $STATEDIR/sessions ]; then
-  find "$STATEDIR/sessions" -type f -mmin +120 | xargs rm -f
-else
-  for i in offline caf dev; do
-    find "$STATEDIR/$i/sessions" -type f -mmin +120 | xargs rm -f
-  done
-fi
+for dir in $(find $STATEDIR -maxdepth 2 -type d -name sessions); do
+  find "$dir" -type f -mmin +120 | xargs rm -f
+done
 
 ######################################################################
 # Delete transfered zip files
-if [ -d $STATEDIR/offline ]; then
-  for i in offline caf dev; do
-    ZIPREPO=$STATEDIR/$i/zipped
-    CLEANDIR=$STATEDIR/$i/agents/clean
-
+for i in offline caf dev; do
+  ZIPREPO=$STATEDIR/$i/zipped
+  CLEANDIR=$STATEDIR/$i/agents/clean
+  if [ -d $ZIPREPO ] && [ -d $CLEANDIR ]; then
     for cf in $(find $CLEANDIR -name \*.zinfo); do
       set -e
       ZIPPATH=$ZIPREPO/$(python -c "a=eval(file('$cf').read());print a['zpath']")
@@ -49,12 +47,13 @@ if [ -d $STATEDIR/offline ]; then
       fi
       set +e
     done
-  done
-fi
+  fi
+done
 
 ######################################################################
 # Compact monitoring logs.
-if [ -d $FILER ]; then
+if [ -d $FILER/status ]; then
+  HOST=$(hostname -s | tr '[:upper:]' '[:lower:]')
   for f in $(find $FILER/status/*/$HOST/* -name '20[0-9][0-9][01][0-9]*.txt' -mmin +60 | sort); do
     set -e
     [ -f "$f" ] || continue
