Added automatic kinit operation

diff --git a/dqmgui/manage b/dqmgui/manage
--- a/dqmgui/manage
+++ b/dqmgui/manage
@@ -68,6 +68,14 @@ export STAGE_HOST=${STAGE_HOST:-castorcms}
 export RFIO_USE_CASTOR_V2=YES
 export STAGE_SVCCLASS=archive
 
+# kerberos
+principal=`klist -k "$keytab" | tail -1 | awk '{print $2}'`
+kinit $principal -k -t "$keytab" 2>&1 1>& /dev/null
+if [ $? == 1 ]; then
+    echo "Unable to perform kinit"
+    exit 1
+fi
+
 # Set Flavor for HOST:DOMAIN
 case $HOST:$DOMAIN in
   # Anything in the CMS network, will be automatically Online
