Harmonise 'manage' scripts, remove unnecessary boiler-plate.
From: Lassi Tuura <lat@cern.ch>


git-svn-id: svn+ssh://svn.cern.ch/reps/CMSDMWM/Infrastructure/branches/deployment-reorg@11686 4525493e-7705-40b1-a816-d608a930855b

diff --git a/couchdb/manage b/couchdb/manage
--- a/couchdb/manage
+++ b/couchdb/manage
@@ -1,10 +1,27 @@
-#! /bin/bash
+#!/bin/sh
 
-case $(id -un) in cmsweb ) echo "ERROR: please use another account" 1>&2; exit 1;; esac
+##H Usage: manage ACTION [ARG] [SECURITY-STRING]
+##H
+##H Available actions:
+##H   help        show this help
+##H   version     get current version of the service
+##H   status      show current service's status
+##H   sysboot     start server from crond if not running
+##H   restart     (re)start the service
+##H   start       (re)start the service
+##H   stop        stop the service
+##H   pushapps    push couch applications
+##H   compact     compact database ARG
+##H   cleanviews  clean view named ARG
+##H
+##H For more details please refer to operations page:
+##H   https://twiki.cern.ch/twiki/bin/view/CMS/CouchDB
 
-#######################################################
-# Global configuration and environment setup
-#######################################################
+if [ $(id -un)  = cmsweb ]; then
+  echo "ERROR: please use another account" 1>&2
+  exit 1
+fi
+
 ME=$(basename $(dirname $0))
 TOP=$(cd $(dirname $0)/../../.. && pwd)
 ROOT=$(cd $(dirname $0)/../.. && pwd)
@@ -12,33 +29,42 @@ CFGDIR=$(dirname $0)
 LOGDIR=$TOP/logs/$ME
 STATEDIR=$TOP/state/$ME
 KEYFILE=$ROOT/auth/$ME/hmackey.ini
-TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/CouchDB#Starting_the_service"
+COLOR_OK="\\033[0;32m"
+COLOR_WARN="\\033[0;31m"
+COLOR_NORMAL="\\033[0;39m"
+
 . $ROOT/apps/$ME/etc/profile.d/init.sh
 
-#######################################################
-# Actions definition
-#######################################################
-# Function to start the service conditionally on crond restart
-function sysboot {
+# Start service conditionally on crond restart.
+sysboot()
+{
   if couchdb -p $STATEDIR/couchdb.pid -s; then :; else
     start
   fi
 }
 
-# Function to start the service
-start() {
+# Start the service.
+start()
+{
   cd $STATEDIR
   couchdb -A $CFGDIR/ -a $KEYFILE -b \
     -o $LOGDIR/$(date +%Y%m%d-%H%M%S).stdout \
     -e $LOGDIR/$(date +%Y%m%d-%H%M%S).stderr \
     -p $STATEDIR/couchdb.pid </dev/null >/dev/null 2>&1
+
+  sleep 1
+  push_apps
 }
 
-stop() {
+# Stop the service.
+stop()
+{
   couchdb -d -p $STATEDIR/couchdb.pid
 }
 
-status() {
+# Check if the server is running.
+status()
+{
   couchdb -p $STATEDIR/couchdb.pid -s
 
   curl -s localhost:5984 | grep -q '{"couchdb":"Welcome","version":"1.0.1"}' ||
@@ -49,8 +75,10 @@ status() {
   echo $TASKS
 }
 
-# When a view is changed (e.g. new version of an app deployed) the views should be cleaned
-clean_views() {
+# When a view is changed, such as a new app version is deployed,
+# invoke this to clean up the views in that database.
+clean_views()
+{
   local database=$1
   [ -n "$database" ] ||
     { echo "You must specify the database you wish to clean the views "; exit 1; }
@@ -61,7 +89,9 @@ clean_views() {
     { echo "An error occured while cleaning the views. Please look in the CouchDB logs."; exit 3; }
 }
 
-push_apps() {
+# Push applications from staging area into couchdb.
+push_apps()
+{
   for APP in $STATEDIR/stagingarea/*; do
     [ -f $APP ] || continue
     . $APP
@@ -71,8 +101,9 @@ push_apps() {
   done
 }
 
-#Trigger a compaction with: manage compact t1_uk_ral_requests 'I did read documentation'
-compact(){
+# Trigger a database compaction.
+compact()
+{
   local database=$1
   [ -n "$database" ] ||
     { echo "You must specify a database to compact"; exit 3; }
@@ -89,50 +120,70 @@ compact(){
   # curl -H "Content-Type: application/json" -X POST http://localhost:5984/dbname/_compact/designname
 }
 
-help() {
-  echo "CouchDB management script"
-  echo "Usage: $0 status|start|stop|restart|help|version|pushapps security_string"
-  echo "       $0 compact|cleanviews dbname security_string"
-  echo "For more details, check the Twiki page: $TWIKI_PAGE"
-}
-
-check() {
+# Verify the security string.
+check()
+{
   CHECK=$(echo "$1" | md5sum | awk '{print $1}')
   if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
-    echo "$0: cannot complete operation, please read documentation." 1>&2
+    echo "$0: cannot complete operation, please check documentation." 1>&2
     exit 2;
   fi
 }
 
-#######################################################
-# Main
-#######################################################
-
-case $1 in
-  start | restart)
-    check "$2"; stop; sleep 1; start; sleep 1; push_apps; status ;;
-  status)
-    status ;;
-  stop)
-    check "$2"; stop; status ;;
-  pushapps)
-    check "$2"; push_apps;;
-  compact)
-    check "$3"; compact $2;;
-  cleanviews)
-    check "$3"; clean_views $2;;
-  sysboot)
-    if ps -oargs= $PPID | grep -q -e crond; then
+# Main routine, perform action requested on command line.
+case ${1:-status} in
+  sysboot )
+    if ps -oargs= $PPID | grep -q crond; then
       sysboot
     else
       echo "$0: sysboot is for cron only" 1>&2
       exit 1
-    fi ;;
-  help)
-    help ;;
-  version)
-    echo "Management script for CouchDB $COUCHDB_VERSION." ;;
+    fi
+    ;;
+
+  start | restart )
+    check "$2"
+    stop
+    sleep 1
+    start
+    status
+    ;;
+
+  status )
+    status
+    ;;
+
+  stop )
+    check "$2"
+    stop
+    status
+    ;;
+
+  pushapps )
+    check "$2"
+    push_apps
+    ;;
+
+  compact )
+    check "$3"
+    compact $2
+    ;;
+
+  cleanviews )
+    check "$3"
+    clean_views $2
+    ;;
+
+  help )
+    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
+    ;;
+
+  version )
+    echo "$COUCHDB_VERSION"
+    ;;
+
   * )
     echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
-    exit 1 ;;
+    exit 1
+    ;;
 esac
diff --git a/das/manage b/das/manage
--- a/das/manage
+++ b/das/manage
@@ -1,15 +1,23 @@
-#! /bin/bash
+#!/bin/sh
 
-case $(id -un) in cmsweb ) echo "ERROR: please use another account" 1>&2; exit 1;; esac
+##H Usage: manage ACTION [SECURITY-STRING]
+##H
+##H Available actions:
+##H   help        show this help
+##H   version     get current version of the service
+##H   status      show current service's status
+##H   sysboot     start server from crond if not running
+##H   restart     (re)start the service
+##H   start       (re)start the service
+##H   stop        stop the service
+##H
+##H For more details please refer to operations page:
+##H   https://twiki.cern.ch/twiki/bin/view/CMS/DASOperation
 
-#######################################################
-# DAS management script
-#######################################################
-# Setting the basic and common variables.
-# Make sure that these are up to date.
-# If need a new variable, it must be defined here.
-# Use export if you really need this!
-#######################################################
+if [ $(id -un)  = cmsweb ]; then
+  echo "ERROR: please use another account" 1>&2
+  exit 1
+fi
 
 ME=$(basename $(dirname $0))
 TOP=$(cd $(dirname $0)/../../.. && pwd)
@@ -17,10 +25,11 @@ ROOT=$(cd $(dirname $0)/../.. && pwd)
 CFGDIR=$(dirname $0)
 LOGDIR=$TOP/logs/$ME
 STATEDIR=$TOP/state/$ME
-SERVICE_TITLE="DAS"
-TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/DASOperation"
+COLOR_OK="\\033[0;32m"
+COLOR_WARN="\\033[0;31m"
+COLOR_NORMAL="\\033[0;39m"
+
 . $ROOT/apps/$ME/etc/profile.d/init.sh
-cd $STATEDIR
 
 export DAS_ROOT YUI_ROOT
 export PYTHONUNBUFFERED=1
@@ -34,15 +43,11 @@ export X509_USER_CERT=$X509_USER_PROXY
 export X509_USER_KEY=$X509_USER_PROXY
 export DAS_CONFIG=$CFGDIR/das_cms.py
 export DAS_ANALYTICS=$CFGDIR/analytics_cfg.py
+cd $STATEDIR
 
-#######################################################
-# Function for the main actions.
-# If using the variable here, need to define it in the
-# top part of the script, to keep them in one place.
-#######################################################
-
-# Function to start the service conditionally on crond restart
-function sysboot {
+# Start service conditionally on crond restart.
+sysboot()
+{
   dostart=false
   for pat in cache web; do
     if [ $(pgrep -u $(id -u) -f "[/]das_server.py.*=$pat" | wc -l) = 0 ]; then
@@ -52,129 +57,104 @@ function sysboot {
   if [ $(pgrep -u $(id -u) -f "[/]analytics_controller.py" | wc -l) = 0 ]; then
     dostart=true
   fi
-  $dostart && { start; start_analytics; }
+  $dostart && start
 }
 
-# Function which is used to start the service
-function start {
-  echo "Starting the $SERVICE_TITLE"
+# Start the service.
+start()
+{
+  echo "starting $ME"
   for pat in cache web; do
     python -u $DAS_PYTHONPATH/DAS/web/das_server.py --server=$pat \
        </dev/null 2>&1 | rotatelogs $LOGDIR/das-$pat-%Y%m%d.log 86400 >/dev/null 2>&1 &
   done
-}
 
-function start_analytics {
-  echo "Starting the $SERVICE_TITLE analytics"
   python -u $DAS_PYTHONPATH/DAS/analytics/analytics_controller.py $DAS_ANALYTICS \
-       </dev/null 2>&1 | rotatelogs $LOGDIR/das-analytics-%Y%m%d.log 86400 >/dev/null 2>&1 &
+    </dev/null 2>&1 | rotatelogs $LOGDIR/das-analytics-%Y%m%d.log 86400 >/dev/null 2>&1 &
 }
 
-# Function which is used to stop the service
-function stop {
-  echo "Stopping the $SERVICE_TITLE"
+# Stop the service.
+stop()
+{
+  echo "stopping $ME"
   for pat in web cache; do
     for pid in $(pgrep -u $(id -u) -f "[/]das_server.py.*=$pat"); do
       kill -9 $pid
     done
   done
-}
 
-function stop_analytics {
-  echo "Stopping the $SERVICE_TITLE analytics"
   for pid in $(pgrep -u $(id -u) -f "[/]analytics_controller.py"); do
     kill -9 $pid
   done
 }
 
-# Function to chack the status of the process
-function status {
-    for pat in cache web analytics; do
-        if  [ $pat == "cache" ]; then
-            pid=$(pgrep -u $(id -u) -f "[/]das_server.py.*=cache")
-        elif [ $pat == "web" ]; then
-            pid=$(pgrep -u $(id -u) -f "[/]das_server.py.*=web")
-        elif [ $pat == "analytics" ]; then
-            pids=$(pgrep -u $(id -u) -f "[/]analytics_controller.py")
-            pid=`echo $pids | tr '\n' ' '`
-        fi
-        if [ x"$pid" = x ]; then
-            echo "DAS $pat is not running"
-        else
-            echo "DAS $pat is running, PID $pid"
-        fi
-    done
+# Check if the server is running.
+status()
+{
+  for pat in cache web analytics; do
+    if [ $pat == "cache" ]; then
+      pid=$(pgrep -u $(id -u) -f "[/]das_server.py.*=cache" | sort -n)
+    elif [ $pat == "web" ]; then
+      pid=$(pgrep -u $(id -u) -f "[/]das_server.py.*=web" | sort -n)
+    elif [ $pat == "analytics" ]; then
+      pid=$(pgrep -u $(id -u) -f "[/]analytics_controller.py" | sort -n)
+    fi
+    if [ X"$pid" = X ]; then
+      echo -e "$ME $pat is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
+    else
+      echo -e "$ME $pat is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
+    fi
+  done
 }
 
-# Function to provide the help for the user
-function help {
-  echo "$SERVICE_TITLE management script"
-  echo "Usage: $0 status|start|stop|restart|run|help|version security_string"
-  echo "For more details, check the Twiki page: $TWIKI_PAGE"
-}
-
-# Function to check the security string.
-function check {
+# Verify the security string.
+check()
+{
   CHECK=$(echo "$1" | md5sum | awk '{print $1}')
   if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
-    echo "$0: cannot complete operation, please check documentation."
+    echo "$0: cannot complete operation, please check documentation." 1>&2
     exit 2;
   fi
 }
 
-#######################################################
-# The engine of the script. The place where the
-# script reacts to the actions.
-# Params: $1 - action
-#         $2 - security string
-#######################################################
-
-case $1 in
-  sysboot)
-    if ps -oargs= $PPID | grep -q -e crond; then
+# Main routine, perform action requested on command line.
+case ${1:-status} in
+  sysboot )
+    if ps -oargs= $PPID | grep -q crond; then
       sysboot
     else
       echo "$0: sysboot is for cron only" 1>&2
       exit 1
     fi
     ;;
-  start)
+
+  start | restart )
     check "$2"
     stop
     start
-    stop_analytics
-    start_analytics
     status
     ;;
-  schema)
-    check "$2"
-    schema
-    ;;
-  restart)
-    check "$2"
-    stop
-    start "restart"
-    stop_analytics
-    start_analytics
+
+  status )
     status
     ;;
-  status)
-    status
-    ;;
-  stop)
+
+  stop )
     check "$2"
     stop
-    stop_analytics
     status
     ;;
-  help)
-    help
+
+  help )
+    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
     ;;
-  version)
-    echo "Management script for $SERVICE_TITLE $DAS_VERSION."
+
+  version )
+    echo "$DAS_VERSION"
     ;;
+
   * )
     echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
-    exit 1 ;;
+    exit 1
+    ;;
 esac
-
diff --git a/dbsweb/manage b/dbsweb/manage
--- a/dbsweb/manage
+++ b/dbsweb/manage
@@ -1,143 +1,137 @@
-#! /bin/bash
+#!/bin/sh
 
-case $(id -un) in cmsweb ) echo "ERROR: please use another account" 1>&2; exit 1;; esac
+##H Usage: manage ACTION [SECURITY-STRING]
+##H
+##H Available actions:
+##H   help        show this help
+##H   version     get current version of the service
+##H   status      show current service's status
+##H   sysboot     start server from crond if not running
+##H   restart     (re)start the service
+##H   start       (re)start the service
+##H   stop        stop the service
+##H
+##H For more details please refer to operations page:
+##H   https://twiki.cern.ch/twiki/bin/view/CMS/DBS2_discovery
 
-#######################################################
-# DBS Discovery management script
-# Author: Ignas Butenas, contact if needed by email: ignas.butenas@cern.ch
-#######################################################
-# Setting the basic and common variables.
-# Make sure that these are up to date.
-# If need a new variable, it must be defined here.
-# Use export if you really need this!
-#######################################################
+if [ $(id -un)  = cmsweb ]; then
+  echo "ERROR: please use another account" 1>&2
+  exit 1
+fi
+
 ME=$(basename $(dirname $0))
 TOP=$(cd $(dirname $0)/../../.. && pwd)
 ROOT=$(cd $(dirname $0)/../.. && pwd)
 CFGDIR=$(dirname $0)
 LOGDIR=$TOP/logs/$ME
 STATEDIR=$TOP/state/$ME
-SERVICE_TITLE="DBS Discovery"
-TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/DBS2_discovery#Start_Stop_Restart_Data_Discover"
+COLOR_OK="\\033[0;32m"
+COLOR_WARN="\\033[0;31m"
+COLOR_NORMAL="\\033[0;39m"
+
 . $ROOT/apps/dbs-web/etc/profile.d/init.sh
+
 export SEC_MOD_INI=$ROOT/auth/sitedb/security.ini
-port=$(cat $CFGDIR/DBSDD.conf | grep -i "port=" | tail -1 | sed "s/PORT=//g")
-url=$(cat $CFGDIR/DBSDD.conf  | grep -i "^URL=" | tail -1 | sed "s/URL=//g")
-pidfile=$(cat $CFGDIR/DBSDD.conf | grep -i "pidfile=" | tail -1 | sed "s/PIDFILE=//g")
-cmd="cmsWeb --base-url=$url --port=$port --default-page /DDServer --pid-file $pidfile"
+export DDHOME=$DBS_WEB_ROOT/lib/python2.6/site-packages
+export DBS_DBPARAM=$DDHOME/Templates/DBParam
+export DBS_CLIENT_ROOT
+export WEBTOOLS_ROOT
+export YUI_ROOT
+export PYTHONPATH=$DDHOME:$DDHOME/QueryBuilder:$ELEMENTTREE_ROOT/share/lib/python`echo $PYTHON_VERSION | cut -d. -f1,2`/site-packages:$PYTHONPATH
 
-#######################################################
-# Function for the main actions.
-# If using the variable here, need to define it in the
-# top part of the script, to keep them in one place.
-#######################################################
+port=$(perl -ne '/^PORT=(\d+)/ && print $1' < $CFGDIR/DBSDD.conf)
+url=$(perl -ne '/^URL=(\S+)/ && print $1' < $CFGDIR/DBSDD.conf)
+pidfile=$(perl -ne '/^PIDFILE=(\S+)/ && print $1' <$CFGDIR/DBSDD.conf)
 
-# Function to start the service conditionally on crond restart
-function sysboot {
+# Start service conditionally on crond restart.
+sysboot()
+{
   if [ $(pgrep -u $(id -u) -f "[/]DDServer" | wc -l) = 0 ]; then
     start
   fi
 }
 
-# Function which is used to start the service
-function start {
-  echo "Starting the $SERVICE_TITLE"
-  cd $DBS_WEB_ROOT/lib/python2.6/site-packages
-  export DDHOME=$PWD
-  export DBS_DBPARAM=$DDHOME/Templates/DBParam
-  export DBS_CLIENT_ROOT
-  export WEBTOOLS_ROOT
-  export YUI_ROOT
-  export PYTHONPATH=$DDHOME:$DDHOME/QueryBuilder:$ELEMENTTREE_ROOT/share/lib/python`echo $PYTHON_VERSION | cut -d. -f1,2`/site-packages:$PYTHONPATH
-  nohup $cmd </dev/null 2>&1 | rotatelogs $LOGDIR/dbsweb-%Y%m%d.log 86400 >/dev/null 2>&1 &
+# Start the service.
+start()
+{
+  cd $DDHOME
+  echo "starting $ME"
+  cmsWeb --base-url=$url --port=$port --default-page /DDServer \
+    --pid-file $pidfile </dev/null 2>&1 |
+    rotatelogs $LOGDIR/dbsweb-%Y%m%d.log 86400 >/dev/null 2>&1 &
 }
 
-# Function which is used to stop the service
-function stop {
-  echo "Stopping the $SERVICE_TITLE"
-  pid=$(pgrep -u $(id -u) -f "cmsWeb.*=$port.*[/]DDServer")
-  if [ X"$pid" != X ]; then
-    kill -9 $pid
-  fi
+# Stop the service.
+stop()
+{
+  echo "stopping $ME"
+  for PID in $(pgrep -u $(id -u) -f "cmsWeb.*=$port.*[/]DDServer" | sort -rn); do
+    PSLINE=$(ps -o pid=,bsdstart=,args= $PID |
+             perl -n -e 'print join(" ", (split)[0..6])')
+    echo "Stopping $PID ($PSLINE):"
+    kill -9 $PID
+  done
 }
 
-# Function to chack the status of the process
-function status {
-  pid=$(pgrep -u $(id -u) -f "cmsWeb.*=$port.*[/]DDServer")
-  if [ X"$pid" != X ]; then
-    echo "$SERVICE_TITLE is RUNNING, pid=$pid"
-    ps auxw | grep cmsWeb | grep DDServer | grep -v grep | grep $port
+# Check if the server is running.
+status()
+{
+  pid=$(pgrep -u $(id -u) -f "cmsWeb.*=$port.*[/]DDServer" | sort -n)
+  if [ X"$pid" = X ]; then
+    echo -e "$ME is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
   else
-    echo "$SERVICE_TITLE is NOT RUNNING"
+    echo -e "$ME is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
   fi
 }
 
-#######################################################
-# Function to provide the help for the user
-# To edit the help provided, edit lines with the ##H prefix
-#######################################################
-##H Available actions:
-##H   sysboot - start server from crond if not running
-##H   status - show current service's status
-##H   start - start the service
-##H   stop - stop the service
-##H   restart - restart the service
-##H   version - get current version of the service
-##H Security string - string needed to perform actions, see twiki page
-#######################################################
-function help {
-  echo "$SERVICE_TITLE management script"
-  echo "Usage: $0 status|start|stop|restart|help|version security_string"
-  echo "For more details, check the Twiki page: $TWIKI_PAGE"
-  perl -ne '/^##H / && do { s/^##H ?//; print }' < $0
-}
-
-# Function to check the security string.
-function check {
+# Verify the security string.
+check()
+{
   CHECK=$(echo "$1" | md5sum | awk '{print $1}')
   if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
-    echo "$0: cannot complete operation, please check documentation."
+    echo "$0: cannot complete operation, please check documentation." 1>&2
     exit 2;
   fi
 }
 
-#######################################################
-# The engine of the script. The place where the
-# script reacts to the actions.
-# Params: $1 - action
-#         $2 - security string
-#######################################################
-
-case $1 in
-  sysboot)
-    if ps -oargs= $PPID | grep -q -e crond; then
+# Main routine, perform action requested on command line.
+case ${1:-status} in
+  sysboot )
+    if ps -oargs= $PPID | grep -q crond; then
       sysboot
     else
       echo "$0: sysboot is for cron only" 1>&2
       exit 1
     fi
     ;;
-  start | restart)
+
+  start | restart )
     check "$2"
     stop
     start
     status
     ;;
-  status)
+
+  status )
     status
     ;;
-  stop)
+
+  stop )
     check "$2"
     stop
     status
     ;;
-  help)
-    help
+
+  help )
+    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
     ;;
-  version)
-    echo "Management script for $SERVICE_TITLE $DBS_WEB_VERSION."
+
+  version )
+    echo "$DBS_WEB_VERSION"
     ;;
+
   * )
     echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
-    exit 1 ;;
+    exit 1
+    ;;
 esac
diff --git a/filemover/manage b/filemover/manage
--- a/filemover/manage
+++ b/filemover/manage
@@ -1,13 +1,23 @@
-#! /bin/bash
+#!/bin/sh
 
-#######################################################
-# FileMover management script
-#######################################################
-# Setting the basic and common variables.
-# Make sure that these are up to date.
-# If need a new variable, it must be defined here.
-# Use export if you really need this!
-#######################################################
+##H Usage: manage ACTION [SECURITY-STRING]
+##H
+##H Available actions:
+##H   help        show this help
+##H   version     get current version of the service
+##H   status      show current service's status
+##H   sysboot     start server from crond if not running
+##H   restart     (re)start the service
+##H   start       (re)start the service
+##H   stop        stop the service
+##H
+##H For more details please refer to operations page:
+##H   https://twiki.cern.ch/twiki/bin/view/CMS/FileMover
+
+if [ $(id -un)  = cmsweb ]; then
+  echo "ERROR: please use another account" 1>&2
+  exit 1
+fi
 
 ME=$(basename $(dirname $0))
 TOP=$(cd $(dirname $0)/../../.. && pwd)
@@ -15,43 +25,41 @@ ROOT=$(cd $(dirname $0)/../.. && pwd)
 CFGDIR=$(dirname $0)
 LOGDIR=$TOP/logs/$ME
 STATEDIR=$TOP/state/$ME
-SERVICE_TITLE="FileMover"
-TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/FileMover#Starting_the_Service"
+CFGFILE=$CFGDIR/fm_config.py
+COLOR_OK="\\033[0;32m"
+COLOR_WARN="\\033[0;31m"
+COLOR_NORMAL="\\033[0;39m"
+
 . $ROOT/apps/$ME/etc/profile.d/init.sh
 
 export FILEMOVER_ROOT YUI_ROOT
 export X509_USER_PROXY=$STATEDIR/proxy/proxy.cert
 export X509_USER_CERT=$STATEDIR/proxy/proxy.cert
 export X509_USER_KEY=$STATEDIR/proxy/proxy.cert
-FILEMOVER_CONFIG=$CFGDIR/fm_config.py
 
-port=8201 url="/filemover/"
-cmd="$WMCORE_ROOT/lib/python2.6/site-packages/WMCore/WebTools/Root.py --ini=$FILEMOVER_CONFIG"
-
-#######################################################
-#  Function for the main actions.
-#  If using the variable here, need to define it in the
-#  top part of the script, to keep them in one place.
-#######################################################
-
-# Function to start the service conditionally on crond restart
-function sysboot {
-  if [ $(pgrep -u $(id -u) -f "$cmd" | wc -l) = 0 ]; then
+# Start service conditionally on crond restart.
+sysboot()
+{
+  if [ $(pgrep -u $(id -u) -f "Root.py.*[=]$CFGFILE" | wc -l) = 0 ]; then
     start
   fi
 }
 
-# Function to start the service
-function start {
+# Start the service.
+start()
+{
   cd $STATEDIR
-  echo "Starting the $SERVICE_TITLE"
-  nohup ${cmd} </dev/null 2>&1 | rotatelogs $LOGDIR/filemover-%Y%m%d.log 86400 >/dev/null 2>&1 &
+  echo "starting $ME"
+  python $WMCORE_ROOT/lib/python*/site-packages/WMCore/WebTools/Root.py \
+    --ini=$CFGFILE </dev/null 2>&1 |
+    rotatelogs $LOGDIR/filemover-%Y%m%d.log 86400 >/dev/null 2>&1 &
 }
 
-# Function to stop the service
-function stop {
-  echo "Stopping the $SERVICE_TITLE"
-  for PID in $(pgrep -u $(id -u) -f "$cmd" | sort -rn); do
+# Stop the service.
+stop()
+{
+  echo "stopping $ME"
+  for PID in $(pgrep -u $(id -u) -f "Root.py.*[=]$CFGFILE" | sort -rn); do
     PSLINE=$(ps -o pid=,bsdstart=,args= $PID |
              perl -n -e 'print join(" ", (split)[0..6])')
     echo "Stopping $PID ($PSLINE):"
@@ -59,90 +67,66 @@ function stop {
   done
 }
 
-# Function to chack the status of the process
-function status {
-  if [ $(pgrep -u $(id -u) -f "$cmd" | wc -l) != 0 ]; then
-    echo "$SERVICE_TITLE is RUNNING."
+# Check if the server is running.
+status()
+{
+  pid=$(pgrep -u $(id -u) -f "Root.py.*[=]$CFGFILE" | sort -n)
+  if [ X"$pid" = X ]; then
+    echo -e "$ME is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
   else
-    echo "$SERVICE_TITLE is NOT RUNNING."
+    echo -e "$ME is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
   fi
 }
 
-#######################################################
-# Function to provide the help for the user
-# To edit the help provided, edit lines with the ##H prefix
-#######################################################
-##H Available actions:
-##H   sysboot - start server from crond if not running
-##H   status - show current service's status
-##H   start - start the service
-##H   stop - stop the service
-##H   restart - restart the service
-##H   version - get current version of the service
-##H Security string - string needed to perform actions, see twiki page
-#######################################################
-function help {
-  echo "$SERVICE_TITLE management script"
-  echo "Usage: $0 status|start|stop|restart|help|version security_string"
-  echo "For more details, check the Twiki page: $TWIKI_PAGE"
-  perl -ne '/^##H / && do { s/^##H ?//; print }' < $0
-}
-
-# Function to check the security string.
-function check {
+# Verify the security string.
+check()
+{
   CHECK=$(echo "$1" | md5sum | awk '{print $1}')
   if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
-    echo "$0: cannot complete operation, please check documentation."
+    echo "$0: cannot complete operation, please check documentation." 1>&2
     exit 2;
   fi
 }
 
-#######################################################
-# The engine of the script. The place where the
-# script reacts to the actions.
-# Params: $1 - action
-#         $2 - security string
-#######################################################
-
-case $1 in
-  sysboot)
-    if ps -oargs= $PPID | grep -q -e crond; then
+# Main routine, perform action requested on command line.
+case ${1:-status} in
+  sysboot )
+    if ps -oargs= $PPID | grep -q crond; then
       sysboot
     else
       echo "$0: sysboot is for cron only" 1>&2
       exit 1
     fi
     ;;
-  start | restart)
+
+  start | restart )
     check "$2"
     stop
     start
     sleep 2
     status
     ;;
-  status)
+
+  status )
     status
     ;;
-  stop)
+
+  stop )
     check "$2"
     stop
     status
     ;;
-  help)
-    help
+
+  help )
+    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
     ;;
-  version)
-    echo "Management script for $SERVICE_TITLE $FILEMOVER_VERSION."
+
+  version )
+    echo "$FILEMOVER_VERSION"
     ;;
-  stdout)
-    cmd="$cmd --log-level 1000"
-    check "$2"
-    stop
-    start
-    sleep 2
-    status
-    ;;
-  *)
+
+  * )
     echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
-    exit 1 ;;
+    exit 1
+    ;;
 esac
diff --git a/mongodb/manage b/mongodb/manage
--- a/mongodb/manage
+++ b/mongodb/manage
@@ -1,15 +1,23 @@
 #!/bin/sh
 
-case $(id -un) in cmsweb ) echo "ERROR: please use another account" 1>&2; exit 1;; esac
+##H Usage: manage ACTION [SECURITY-STRING]
+##H
+##H Available actions:
+##H   help        show this help
+##H   version     get current version of the service
+##H   status      show current service's status
+##H   sysboot     start server from crond if not running
+##H   restart     (re)start the service
+##H   start       (re)start the service
+##H   stop        stop the service
+##H
+##H For more details please refer to operations page:
+##H   https://twiki.cern.ch/twiki/bin/view/CMS/DASOperation
 
-#######################################################
-# MongoDB management script
-#######################################################
-# Setting the basic and common variables.
-# Make sure that these are up to date.
-# If need a new variable, it must be defined here.
-# Use export if you really need this!
-#######################################################
+if [ $(id -un)  = cmsweb ]; then
+  echo "ERROR: please use another account" 1>&2
+  exit 1
+fi
 
 ME=$(basename $(dirname $0))
 TOP=$(cd $(dirname $0)/../../.. && pwd)
@@ -17,24 +25,21 @@ ROOT=$(cd $(dirname $0)/../.. && pwd)
 CFGDIR=$(dirname $0)
 LOGDIR=$TOP/logs/$ME
 STATEDIR=$TOP/state/$ME
-SERVICE_TITLE="MongoDB"
-TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/DASOperation"
+COLOR_OK="\\033[0;32m"
+COLOR_WARN="\\033[0;31m"
+COLOR_NORMAL="\\033[0;39m"
+
 . $ROOT/apps/mongo/etc/profile.d/init.sh
 cd $STATEDIR
 
-#######################################################
-#  Function for the main actions.
-#  If using the variable here, need to define it in the
-#  top part of the script, to keep them in one place.
-#######################################################
-
-# Function to clean-up and update specific DB in Mongo
-# it accepts a single parameter in a form <dbname>_<collection_name>,
-# e.g. mapping_db
-# First it uses a cleanup script, e.g. clean_mapping_db.js to clean DB content
-# then use update script to populate new content into DB, e.g. update_mapping_db.js
-# The update script contains a JSON docs to be populated.
-function update_db {
+# Function to clean-up and update specific DB in Mongo.
+# Accepts a single parameter in a form <dbname>_<collection_name>,
+# e.g. mapping_db. First runs the cleanup script to clean database
+# content, then uses the update script to populate new content into
+# DB, e.g. clean_mapping_db.js and update_mapping_db.js. The update
+# script contains the JSON docs to be populated.
+update_db()
+{
   stamp=$(cat stagingarea/update_$1.js | md5sum)
   oldstamp=$(cat stagingarea/$1-schema-stamp 2>/dev/null)
   if [ ! -f stagingarea/$1-schema-stamp ] || [ X"$oldstamp" != X"$stamp" ]; then
@@ -49,35 +54,35 @@ function update_db {
   fi
 }
 
-# Function to start the service conditionally on crond restart
-function sysboot {
+# Start service conditionally on crond restart.
+sysboot()
+{
   PID=$(cat $STATEDIR/db/mongod.lock 2>/dev/null)
   if [ X"$PID" = X ] || [ $(ps h $PID | wc -l) = 0 ]; then
     # must clean-up improper shutdown
     rm -rf $STATEDIR/db/*
     rm -f $PWD/stagingarea/*-schema-stamp
     start
-    sleep 2
-    update_db "mapping_db"
   fi
 }
 
-# Function to start the service
-function start()
+# Start the service.
+start()
 {
-  echo "Starting the $SERVICE_TITLE"
+  echo "starting $ME"
   $MONGO_ROOT/bin/mongod --dbpath=$STATEDIR/db \
       --port 8230 --nohttpinterface --bind_ip 127.0.0.1 \
       </dev/null 2>&1 | rotatelogs $LOGDIR/mongodb-%Y%m%d.log 86400 >/dev/null 2>&1 &
   sleep 2
-  echo
-  echo "$SERVICE_TITLE is ready"
+  echo "$ME is ready"
+  sleep 2
+  update_db "mapping_db"
 }
 
-# Function to stop the service
-function stop()
+# Stop the service.
+stop()
 {
-  echo "Stopping the $SERVICE_TITLE"
+  echo "stopping $ME"
   PID=$(cat $STATEDIR/db/mongod.lock 2>/dev/null)
   if [ X"$PID" != X ]; then
     kill -INT $PID
@@ -90,85 +95,65 @@ function stop()
   fi
 }
 
-# Function to check the status of the process
-function status()
+# Check if the server is running.
+status()
 {
   PID=$(cat $STATEDIR/db/mongod.lock 2>/dev/null)
   if [ X"$PID" != X ] && [ $(ps -p $PID | wc -l) != 0 ]; then
-    echo "$SERVICE_TITLE is RUNNING, PID $PID."
+    echo -e "$ME is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
   else
-    echo "$SERVICE_TITLE is NOT RUNNING."
+    echo -e "$ME is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
   fi
 }
 
-#######################################################
-# Function to provide the help for the user
-# To edit the help provided, edit lines with the ##H prefix
-#######################################################
-##H Available actions:
-##H   sysboot - start server from crond if not running
-##H   status - show current service's status
-##H   start - start the service
-##H   stop - stop the service
-##H   restart - restart the service
-##H   version - get current version of the service
-##H Security string - string needed to perform actions, see twiki page
-#######################################################
-function help {
-  echo "$SERVICE_TITLE management script"
-  echo "Usage: $0 status|start|stop|restart|help|version security_string"
-  echo "For more details, check the Twiki page: $TWIKI_PAGE"
-  perl -ne '/^##H / && do { s/^##H ?//; print }' < $0
-}
-
-# Function to check the security string.
-function check {
+# Verify the security string.
+check()
+{
   CHECK=$(echo "$1" | md5sum | awk '{print $1}')
   if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
-    echo "$0: cannot complete operation, please check documentation."
+    echo "$0: cannot complete operation, please check documentation." 1>&2
     exit 2;
   fi
 }
 
-#######################################################
-# The engine of the script. The place where the
-# script reacts to the actions.
-# Params: $1 - action
-#         $2 - security string
-#######################################################
-
-case $1 in
-  sysboot)
-    if ps -oargs= $PPID | grep -q -e crond; then
+# Main routine, perform action requested on command line.
+case ${1:-status} in
+  sysboot )
+    if ps -oargs= $PPID | grep -q crond; then
       sysboot
     else
       echo "$0: sysboot is for cron only" 1>&2
       exit 1
     fi
     ;;
-  start | restart)
+
+  start | restart )
     check "$2"
     stop
     start
-    sleep 2
-    update_db "mapping_db"
     status
     ;;
-  status)
+
+  status )
     status
     ;;
-  stop)
+
+  stop )
     check "$2"
     stop
     status
     ;;
-  help)
-    help
+
+  help )
+    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
     ;;
-  version)
-    echo "Management script for $SERVICE_TITLE."
+
+  version )
+    echo "$MONGO_VERSION"
     ;;
-  *)
+
+  * )
     echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
-    exit 1 ;;
+    exit 1
+    ;;
 esac
diff --git a/phedex/manage b/phedex/manage
--- a/phedex/manage
+++ b/phedex/manage
@@ -1,16 +1,25 @@
-#! /bin/bash
+#!/bin/sh
 
-case $(id -un) in cmsweb ) echo "ERROR: please use another account" 1>&2; exit 1;; esac
+##H Usage: manage ACTION [SECURITY-STRING]
+##H
+##H Available actions:
+##H   help        show this help
+##H   version     get current version of the service
+##H   status      show current service's status
+##H   sysboot     start server from crond if not running
+##H   restart     (re)start the service
+##H   start       (re)start the service
+##H   rgraphs     (re)start only the graphs service
+##H   graceful    restart the service gracefully
+##H   stop        stop the service
+##H
+##H For more details please refer to operations page:
+##H   https://twiki.cern.ch/twiki/bin/view/CMS/PhedexOperationsWebSite
 
-#######################################################
-# Phedex-WEB management script
-# Author: Ignas Butenas, contact if needed by email: ignas.butenas@cern.ch
-#######################################################
-# Setting the basic and common variables.
-# Make sure that these are up to date.
-# If need a new variable, it must be defined here.
-# Use export if you really need this!
-#######################################################
+if [ $(id -un)  = cmsweb ]; then
+  echo "ERROR: please use another account" 1>&2
+  exit 1
+fi
 
 ME=$(basename $(dirname $0))
 TOP=$(cd $(dirname $0)/../../.. && pwd)
@@ -18,10 +27,12 @@ ROOT=$(cd $(dirname $0)/../.. && pwd)
 CFGDIR=$(dirname $0)
 LOGDIR=$TOP/logs/$ME
 STATEDIR=$TOP/state/$ME
-SERVICE_TITLE="PhEDEx"
-TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/PhedexOperationsWebSite#WebStart"
 PHEDEX_PATTERN="/httpd -f $STATEDIR/server.conf"
 GRAPHS_PATTERN="phedex-web.*[/]graphs_website_prod.xml"
+COLOR_OK="\\033[0;32m"
+COLOR_WARN="\\033[0;31m"
+COLOR_NORMAL="\\033[0;39m"
+
 for app in PHEDEX-{datasvc,web,webapp}; do
   . $ROOT/apps/$app/etc/profile.d/init.sh
 done
@@ -31,27 +42,17 @@ export PYTHONPATH=$PHEDEX_GRAPHS_ROOT/src:$GLOBAL_GRAPHS_ROOT/src:$PYTHONPATH
 export GLOBAL_GRAPHS_ROOT # for the .xml files
 export MPLCONFIGDIR=$STATEDIR
 
-#######################################################
-# Function for the main actions.
-# If using the variable here, need to define it in the
-# top part of the script, to keep them in one place.
-#######################################################
-# Function to start the service conditionally on crond restart
-function sysboot {
-  if [ $(pgrep -u $(id -u) -f "$PHEDEX_PATTERN" | wc -l) = 0 ] ||
-     [ $(pgrep -u $(id -u) -f "$GRAPHS_PATTERN" | wc -l) = 0 ]; then
-    start
-  fi
-}
-
-# Start the graphs service
-function start_graphs {
+# Start just the graphs server.
+start_graphs()
+{
+  cd $STATEDIR
   python -u $PHEDEX_GRAPHS_ROOT/tools/phedex-web.py $STATEDIR/etc/graphs_website_prod.xml \
     </dev/null 2>&1 | rotatelogs $LOGDIR/graphs-%Y%m%d.log 86400 >/dev/null 2>&1 &
 }
 
-# Stop the graphs service
-function kill_graphs {
+# Stop just the graphs server.
+kill_graphs()
+{
   for PID in $(pgrep -u $(id -u) -f "$GRAPHS_PATTERN" | sort -rn); do
     PSLINE=$(ps -o pid=,bsdstart=,args= $PID |
              perl -n -e 'print join(" ", (split)[0..6])')
@@ -60,118 +61,125 @@ function kill_graphs {
   done
 }
 
-# Function which is used to start the service
-function start {
+# Start service conditionally on crond restart.
+sysboot()
+{
+  if [ $(pgrep -u $(id -u) -f "$PHEDEX_PATTERN" | wc -l) = 0 ] ||
+     [ $(pgrep -u $(id -u) -f "$GRAPHS_PATTERN" | wc -l) = 0 ]; then
+    start
+  fi
+}
+
+# Start the service.
+start()
+{
   cd $STATEDIR
-  echo "Starting the $SERVICE_TITLE"
+  echo "starting $ME"
   $STATEDIR/etc/httpd start </dev/null 2>&1
   start_graphs
 }
 
-# Function which is used to stop the service
-function stop {
-  echo "Stopping the $SERVICE_TITLE"
-  $STATEDIR/etc/httpd stop
-  kill_graphs
+# Stop the service.
+stop()
+{
+  echo "stopping $ME"
+  for pat in "$PHEDEX_PATTERN" "$GRAPHS_PATTERN"; do
+    for PID in $(pgrep -u $(id -u) -f "$pat" | sort -rn); do
+      PSLINE=$(ps -o pid=,bsdstart=,args= $PID |
+               perl -n -e 'print join(" ", (split)[0..6])')
+      echo "Stopping $PID ($PSLINE):"
+      kill -INT $PID
+      sleep 1
+      kill -9 $PID 2>/dev/null
+    done
+  done
 }
 
-# Function to check the status of the process
-function status {
-  echo "Checking the $SERVICE_TITLE status..."
-  $STATEDIR/etc/httpd status
-
-  GPIDS=$(pgrep -u $(id -u) -f "$GRAPHS_PATTERN" | sort -rn)
-  if [ X"$GPIDS" != X ]; then
-    echo "PhEDEx graph service is RUNNING, PID: $GPIDS"
+# Check if the server is running.
+status()
+{
+  pid=$(pgrep -u $(id -u) -f "$PHEDEX_PATTERN" | sort -n)
+  if [ X"$pid" = X ]; then
+    echo -e "$ME is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
   else
-    echo "PhEDEx graph service is NOT RUNNING."
+    echo -e "$ME is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
+  fi
+
+  pid=$(pgrep -u $(id -u) -f "$GRAPHS_PATTERN" | sort -rn)
+  if [ X"$pid" = X ]; then
+    echo -e "$ME grapher is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
+  else
+    echo -e "$ME grapher is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
   fi
 }
 
-# Function to do graceful restart
-function graceful {
-  echo "Restarting gracefully the $SERVICE_TITLE"
+graceful()
+{
+  echo "restarting $ME gracefully"
   $STATEDIR/etc/httpd graceful
 }
 
-#######################################################
-# Function to provide the help for the user
-# To edit the help provided, edit lines with the ##H prefix
-#######################################################
-##H Available actions:
-##H   status - show current service's status
-##H   start - start the service
-##H   stop - stop the service
-##H   restart - restart the service
-##H   graceful - restart the service gracefully
-##H   rgraphs - restart only the graphs service
-##H   version - get current version of the service
-##H Security string - string needed to perform actions, see twiki page
-#######################################################
-function help {
-  echo "$SERVICE_TITLE management script"
-  echo "Usage: $0 status|start|stop|restart|rgraphs|help|version security_string"
-  echo "For more details, check the Twiki page: $TWIKI_PAGE"
-  perl -ne '/^##H / && do { s/^##H ?//; print }' < $0
-}
-
-# Function to check the security string.
-function check {
+# Verify the security string.
+check()
+{
   CHECK=$(echo "$1" | md5sum | awk '{print $1}')
   if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
-    echo "$0: cannot complete operation, please check documentation."
+    echo "$0: cannot complete operation, please check documentation." 1>&2
     exit 2;
   fi
 }
 
-#######################################################
-# The engine of the script. The place where the
-# script reacts to the actions.
-# Params: $1 - action
-#         $2 - security string
-#######################################################
-
-case $1 in
-  sysboot)
-    if ps -oargs= $PPID | grep -q -e crond; then
+# Main routine, perform action requested on command line.
+case ${1:-status} in
+  sysboot )
+    if ps -oargs= $PPID | grep -q crond; then
       sysboot
     else
       echo "$0: sysboot is for cron only" 1>&2
       exit 1
-    fi ;;
-  start | restart)
+    fi
+    ;;
+
+  start | restart )
     check "$2"
     stop
     start
     status
     ;;
-  status)
+
+  status )
     status
     ;;
-  stop)
+
+  stop )
     check "$2"
     stop
     status
     ;;
-  graceful)
+
+  graceful )
     check "$2"
     graceful
     status
     ;;
-  rgraphs)
+
+  rgraphs )
     check "$2"
-    cd $STATEDIR
     kill_graphs
     start_graphs
     status
     ;;
-  help)
-    help
+
+  help )
+    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
     ;;
-  version)
-    echo "Management script for $SERVICE_TITLE."
+
+  version )
+    echo "$PHEDEX_WEB_VERSION $PHEDEX_DATASVC_VERSION $PHEDEX_WEBAPP_VERSION"
     ;;
+
   * )
     echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
-    exit 1 ;;
+    exit 1
+    ;;
 esac
diff --git a/reqmgr/manage b/reqmgr/manage
--- a/reqmgr/manage
+++ b/reqmgr/manage
@@ -1,12 +1,23 @@
-#! /bin/sh
+#!/bin/sh
 
-case $(id -un) in cmsweb ) echo "ERROR: please use another account" 1>&2; exit 1;; esac
+##H Usage: manage ACTION [SECURITY-STRING]
+##H
+##H Available actions:
+##H   help        show this help
+##H   version     get current version of the service
+##H   status      show current service's status
+##H   sysboot     start server from crond if not running
+##H   restart     (re)start the service
+##H   start       (re)start the service
+##H   stop        stop the service
+##H
+##H For more details please refer to operations page:
+##H   https://twiki.cern.ch/twiki/bin/view/CMS/ReqMgrSystemDesign
 
-#######################################################
-# About the script
-#######################################################
-# Setting the common variables
-#######################################################
+if [ $(id -un)  = cmsweb ]; then
+  echo "ERROR: please use another account" 1>&2
+  exit 1
+fi
 
 ME=$(basename $(dirname $0))
 TOP=$(cd $(dirname $0)/../../.. && pwd)
@@ -14,37 +25,38 @@ ROOT=$(cd $(dirname $0)/../.. && pwd)
 CFGDIR=$(dirname $0)
 LOGDIR=$TOP/logs/$ME
 STATEDIR=$TOP/state/$ME
-SERVICE_TITLE="reqmgr"
-TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/ReqMgrSystemDesign"
-PROJ_CONFIG_FILE=$CFGDIR/ReqMgrConfig.py
+CFGFILE=$CFGDIR/ReqMgrConfig.py
+COLOR_OK="\\033[0;32m"
+COLOR_WARN="\\033[0;31m"
+COLOR_NORMAL="\\033[0;39m"
+
 . $ROOT/apps/$ME/etc/profile.d/init.sh
 
 export PYTHONPATH=$ROOT/auth/$ME:$PYTHONPATH
 export YUI_ROOT
 
-#######################################################
-# Functions for the main actions.
-#######################################################
-
-# Function to start service conditionally on crond restart
-function sysboot {
-  if [ $(pgrep -u $(id -u) -f "Root.py.*[=]$PROJ_CONFIG_FILE" | wc -l) = 0 ]; then
+# Start service conditionally on crond restart.
+sysboot()
+{
+  if [ $(pgrep -u $(id -u) -f "Root.py.*[=]$CFGFILE" | wc -l) = 0 ]; then
     start
   fi
 }
 
-# Function to start the service
-function start {
+# Start the service.
+start()
+{
   cd $STATEDIR
-  echo "Starting the $SERVICE_TITLE"
-  python $WTBASE/WMCore/WebTools/Root.py --ini=$PROJ_CONFIG_FILE \
+  echo "starting $ME"
+  python $WTBASE/WMCore/WebTools/Root.py --ini=$CFGFILE \
     </dev/null 2>&1 | rotatelogs $LOGDIR/reqmgr-%Y%m%d.log 86400 >/dev/null 2>&1 &
 }
 
-# Function which is used to stop the service
-function stop {
-  echo "Stopping the $SERVICE_TITLE"
-  for PID in $(pgrep -u $(id -u) -f "Root.py.*[=]$PROJ_CONFIG_FILE" | sort -rn); do
+# Stop the service.
+stop()
+{
+  echo "stopping $ME"
+  for PID in $(pgrep -u $(id -u) -f "Root.py.*[=]$CFGFILE" | sort -rn); do
     PSLINE=$(ps -o pid=,bsdstart=,args= $PID |
              perl -n -e 'print join(" ", (split)[0..6])')
     echo "Stopping $PID ($PSLINE):"
@@ -52,79 +64,65 @@ function stop {
   done
 }
 
-# Function to chack the status of the process
-function status {
-  if [ $(pgrep -u $(id -u) -f "Root.py.*[=]$PROJ_CONFIG_FILE" | wc -l) != 0 ]; then
-    echo "$SERVICE_TITLE is RUNNING."
+# Check if the server is running.
+status()
+{
+  pid=$(pgrep -u $(id -u) -f "Root.py.*[=]$CFGFILE" | sort -n)
+  if [ X"$pid" = X ]; then
+    echo -e "$ME is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
   else
-    echo "$SERVICE_TITLE is NOT RUNNING."
+    echo -e "$ME is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
   fi
-
 }
 
-#######################################################
-# Function to provide the help for the user
-# To edit the help provided, edit lines with the ##H prefix
-#######################################################
-##H Available actions:
-##H   sysboot - start server from crond if not running
-##H   status - show current service's status
-##H   start - start the service
-##H   stop - stop the service
-##H   restart - restart the service
-##H Security string - string needed to perform actions, see twiki page
-#######################################################
-function help {
-  echo "$SERVICE_TITLE management script"
-  echo "Usage: $0 status|start|stop|restart|help security_string"
-  echo "For more details, check the Twiki page: $TWIKI_PAGE"
-  perl -ne '/^##H / && do { s/^##H ?//; print }' < $0
-}
-
-# Verify the security string. You shouldn't change this.
-function check {
+# Verify the security string.
+check()
+{
   CHECK=$(echo "$1" | md5sum | awk '{print $1}')
   if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
-    echo "$0: cannot complete operation, please check documentation."
+    echo "$0: cannot complete operation, please check documentation." 1>&2
     exit 2;
   fi
 }
 
-#######################################################
-# The engine of the script. The place where the
-# script reacts to the actions.
-# Params: $1 - action
-#         $2 - security string
-#######################################################
-
-case $1 in
-  sysboot)
-    if ps -oargs= $PPID | grep -q -e crond; then
+# Main routine, perform action requested on command line.
+case ${1:-status} in
+  sysboot )
+    if ps -oargs= $PPID | grep -q crond; then
       sysboot
     else
       echo "$0: sysboot is for cron only" 1>&2
       exit 1
     fi
     ;;
-  start | restart)
+
+  start | restart )
     check "$2"
     stop
     start
     status
     ;;
-  status)
+
+  status )
     status
     ;;
-  stop)
+
+  stop )
     check "$2"
     stop
     status
     ;;
-  help)
-    help
-    ;;
-  * )
-    echo "$0: unknown action '$1'. Please read the documentation or run '$0 help'." 1>&2
-    exit 1 ;;
-esac
 
+  help )
+    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
+    ;;
+
+  version )
+    echo "$REQMGR_VERSION"
+    ;;
+
+  * )
+    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
+    exit 1
+    ;;
+esac
