Add script for running backups and archiving into castor.

diff --git a/couchdb/manage b/couchdb/manage
--- a/couchdb/manage
+++ b/couchdb/manage
@@ -15,14 +15,14 @@
 ##H   compact         compact database ARG
 ##H   compactviews    compact database views for design doc ARG ARG
 ##H   cleanviews      clean view named ARG
+##H   backup          rsync databases to ARG (i.e. [user@]host:path)
+##H   archive         archive backups to ARG area in castor
 ##H
 ##H For more details please refer to operations page:
 ##H   https://twiki.cern.ch/twiki/bin/view/CMS/CouchDB
 
-if [ $(id -un)  = cmsweb ]; then
-  echo "ERROR: please use another account" 1>&2
-  exit 1
-fi
+[ $(id -un) != cmsweb -o "$1" = "backup" -o "$1" = "archive" ] ||
+  { echo "ERROR: please use another account" 1>&2; exit 1; }
 
 case $(uname) in Darwin )
   md5sum() { md5 -r ${1+"$@"}; }
@@ -39,6 +39,9 @@ KEYFILE=$ROOT/auth/$ME/hmackey.ini
 COLOR_OK="\\033[0;32m"
 COLOR_WARN="\\033[0;31m"
 COLOR_NORMAL="\\033[0;39m"
+PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/kerberos/bin
+export STAGE_HOST=${STAGE_HOST:-castorcms}
+export RFIO_USE_CASTOR_V2=YES
 
 . $ROOT/apps/$ME/etc/profile.d/init.sh
 
@@ -216,6 +219,43 @@ compact_views()
     { echo "An error occured triggering view compaction. Please look in the CouchDB logs."; exit 7; }
 }
 
+# Rsync couchdb databases to elsewhere (can be used to restore a backup too)
+backup()
+{
+  local hostdir=$1
+  [ -n "$hostdir" ] ||
+    { echo "You must specify a destination [user@]host:path."; exit 9; }
+  rsync --delete -au -e 'ssh -c arcfour' $STATEDIR/database/ $hostdir/ ||
+    { echo "failed to synchronise databases to $hostdir: $?" 1>&2; exit 11; }
+}
+
+# Archive couchdb backups to castor
+archive()
+{
+  local archdir=$1
+  klist -s ||
+    { echo "You must have a valid kerberos token to run the archive." 1>&2; exit 20; }
+  rfstat $archdir >/dev/null ||
+    { echo "Could not stat $archdir in the castor archive" 1>&2; exit 19; }
+
+  echo "Checking for couchdb archives not yet staged out to tape:"
+  stager_qry -M $archdir | grep couchdb | grep -v STAGED || echo "All staged out."
+
+  echo "Starting to archive couchdb backups on $(date)"
+  for bkp in $STATEDIR/backup/*; do
+    [ -d $bkp ] || continue;
+    tarfile=couchdb_${bkp##*/}_$(date +%Y%m%d-%H%M).tar
+    echo "$archdir/$tarfile"
+    tar cf - -C $bkp . | rfcp - $archdir/$tarfile &
+  done
+  wait;
+  [ -n "$tarfile" ] && echo "Archive copy to castor completed on $(date)." ||
+    echo "No backups found on $STATEDIR/backup. Nothing to archive."
+
+  #FIXME: do some sanity checks on castor to make sure new archives are genuine
+  #FIXME: cleanup old archives from castor
+}
+
 # Verify the security string.
 check()
 {
@@ -271,6 +311,16 @@ case ${1:-status} in
   cleanviews )
     check "$3"
     clean_views $2
+    ;;
+
+  backup )
+    check "$3"
+    backup $2
+    ;;
+
+  archive )
+    check "$3"
+    archive $2
     ;;
 
   help )
diff --git a/dqmgui/manage b/dqmgui/manage
--- a/dqmgui/manage
+++ b/dqmgui/manage
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-##H Usage 1: manage [options] ACTION [SECURITY-STRING]
+##H Usage 1: manage [options] ACTION [ARG] [SECURITY-STRING]
 ##H
 ##H Available actions:
 ##H   help        show this help
@@ -12,6 +12,7 @@
 ##H   start       (re)start the service
 ##H   stop        stop the service
 ##H   compile     refresh render plugins
+##H   backup      backup the current service state by archiving it to ARG area in castor
 ##H
 ##H Usage 2: manage [options] ACTION COMPONENTs [SECURITY-STRING]
 ##H COMPONENTs: webserver collector renderer logger agents afs-sync migration
@@ -50,6 +51,7 @@ CONFIGS=
 QUIET=false
 FLAVOR=dev
 ALTERNATIVE_USER=$(stat $TOP -c %U)
+PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/kerberos/bin
 
 case $HOST in
   vocms139 )
@@ -687,6 +689,28 @@ compile()
   done
 }
 
+# Backups dqmgui by archiving its state to castor
+backup()
+{
+  local archdir=$1
+  klist -s ||
+    { echo "You must have a valid kerberos token to run the backup." 1>&2; exit 20; }
+  rfstat $archdir >/dev/null ||
+    { echo "Could not stat $archdir in the castor archive" 1>&2; exit 19; }
+
+  echo "Checking for DQMGUI backups not yet staged out to tape:"
+  stager_qry -M $archdir | grep dqmgui_$HOST | grep -v STAGED || echo "All staged out."
+
+  echo "Starting $HOST DQMGUI backup on $(date)"
+  tarfile=dqmgui_${HOST}_$(date +%Y%m%d-%H%M).tar
+  # FIXME: stop the agents vidDQMImportDaemon visDQMDeleteDaemon to make the index read only
+  tar cf - -C $STATEDIR . | rfcp - $archdir/$tarfile ||
+    { echo "Could not rfcp to $archdir/$tarfile. Backup failed." 1>&2; exit 21; }
+  echo "Completed copying backup to castor on $(date)."
+  # FIXME: start the agents vidDQMImportDaemon visDQMDeleteDaemon if they were running before
+  # FIXME: cleanup from castor older backups
+}
+
 # Verify the security string.
 check()
 {
@@ -772,6 +796,11 @@ case ${1:-status} in
   xstop )
     check "$3"
     stop "$2"
+    ;;
+
+  backup )
+    check "$3"
+    backup "$2"
     ;;
 
   help )
