Changes to separate DAS/MongoDB; MongoDB will run as stand-alone service and it will not know anything about DAS; DAS service will take care how to upload DAS maps into MongoDB (it will take care about MongoDB status)

diff --git a/das/manage b/das/manage
--- a/das/manage
+++ b/das/manage
@@ -10,7 +10,9 @@
 ##H   restart     (re)start the service
 ##H   start       (re)start the service
 ##H   stop        stop the service
-##H   bootstrap   fetch dtata from services: accepted input values and what fields available in services results
+##H   bootstrap   fetch data from services: accepted input values and what fields available in services results
+##H   fetchmaps   fetch DAS maps
+##H   uploadmaps  upload new DAS maps into MongoDB
 ##H
 ##H For more details please refer to operations page:
 ##H   https://twiki.cern.ch/twiki/bin/view/CMS/DASOperation
@@ -51,8 +53,32 @@ export X509_USER_CERT=$X509_USER_PROXY
 export X509_USER_KEY=$X509_USER_PROXY
 export DAS_CONFIG=$CFGDIR/das_cms.py
 export DAS_KWS_IR_INDEX=$STATEDIR/kws_index
+export STAGEDIR=$STATEDIR/stagingarea
+mkdir -p $STAGEDIR
 
 cd $STATEDIR
+host=`hostname`
+
+# helper function to check MongoDB
+check_mongodb() {
+  mongo_pid=`pgrep -f "bin/mongod"`
+  if [ -n "$mongo_pid" ]; then
+      echo "MongoDB pid=$mongo_pid"
+  else
+      echo "MongoDB is not ready, unable to start DAS"
+      exit 1
+  fi
+}
+
+# deploy DAS and DAS KWS maps into stagedir area
+deploy_das_maps(){
+  if [ ! -f $STAGEDIR/das_maps_status ]; then
+      # fresh release, need to copy maps from release area
+      cp $DAS_PYTHONPATH/DAS/services/cms_maps/*.js $STAGEDIR
+      # mark that we updated MongoDB with DAS maps
+      echo "Release maps: `date`" > $STAGEDIR/das_maps_status
+  fi
+}
 
 # Start service conditionally on crond restart.
 sysboot()
@@ -64,27 +90,30 @@ sysboot()
   $dostart && start
 }
 
-# Start the service.
 start()
 {
   echo "starting $ME"
-  python -u $DAS_PYTHONPATH/DAS/web/das_server.py \
-       </dev/null 2>&1 | rotatelogs $LOGDIR/das-%Y%m%d.log 86400 >/dev/null 2>&1 &
+  case $host in vocms133 ) tbed="_testbed" dbspace="_int";; * ) tbed="" dbspace="_prod";; esac
+  deploy_das_maps
+  local mapfile=$STAGEDIR/das${tbed}_maps_dbs${dbspace}.js
+  local kwsmaps=$DAS_KWS_IR_INDEX
+  DAS_MAP_FILE=$mapfile DAS_KWS_MAPS=$kwsmaps $DAS_ROOT/bin/das_server start \
+      </dev/null 2>&1 | rotatelogs $LOGDIR/das-%Y%m%d.log 86400 >/dev/null 2>&1 &
 }
 
 # Stop the service.
 stop()
 {
   echo "stopping $ME"
-  for pid in $(pgrep -u $(id -u) -f "[/]das_server.py"); do
-      kill -9 $pid
+  for das_pid in $(pgrep -u $(id -u) -f "[/]das_server"); do
+      kill -9 $das_pid
   done
 }
 
 # Check if the server is running.
 status()
 {
-  pid=$(pgrep -u $(id -u) -f "[/]das_server.py" | sort -n)
+  local pid=$(pgrep -u $(id -u) -f "[/]das_server" | sort -n)
   if [ X"$pid" = X ]; then
     echo $echo_e "$ME $pat is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
   else
@@ -92,23 +121,62 @@ status()
   fi
 }
 
+# download metadata and stage it for update
+# change is applied on next updatedata() call
+fetch_metadata(){
+  # clean-up STEGEDIR area
+  rm -f $STAGEDIR/*.js $STAGEDIR/*-schema-stamp
+
+  # fetch DAS maps
+  $CFGDIR/metadata_updater/fetch_metadata $STAGEDIR
+
+  # mark that we updated MongoDB with DAS maps
+  echo "Fetched maps: `date`" > $STAGEDIR/das_maps_status
+}
+
+# upload DAS & KWS maps into MognoDB
+upload_das_maps(){
+  # choose appropriate dasmaps to use
+  case $host in vocms133 ) tbed="_testbed" dbspace="_int";; * ) tbed="" dbspace="_prod";; esac
+  local dasmaps=$STAGEDIR/das${tbed}_maps_dbs${dbspace}.js
+
+  # upload DAS and KWS maps into MongoDB
+  $DAS_ROOT/bin/das_update_database $dasmaps $STAGEDIR
+}
+
+# update metadata
+update_metadata(){
+  # check if MongoDB is present
+  check_mongodb
+
+  # upload DAS maps
+  upload_das_maps
+
+  # mark that we updated MongoDB with DAS maps
+  echo "Updated maps: `date`" > $STAGEDIR/das_maps_status
+}
+
+# reset DAS metadata (dasmaps, etc) to the default coming from installation
+reset_metadata(){
+  # clean timestamps
+  rm -f $STAGEDIR/*-schema-stamp
+
+  # copy DAS maps from release to staging area
+  cp -f $DAS_PYTHONPATH/DAS/services/cms_maps/*.js $STAGEDIR
+
+  # upload DAS maps
+  upload_das_maps
+
+  # mark that we updated MongoDB with DAS maps
+  echo "Release maps: `date`" > $STAGEDIR/das_maps_status
+}
+
 # Bootstrap keyword search
 bootstrap()
 {
-    echo "starting keyword search bootstrap (values, fields)"
-    das_bootstrap_kws
-    echo "bootstrap done"
-}
-
-# Exports kws_data, including keylearning
-kws_export_data()
-{
-    echo "starting exporting KWS data"
-    outdir=$STATEDIR/kws_data_exported
-    rm -rf $outdir
-    mkdir -p $outdir
-    das_kws_export_data $outdir
-    echo "KWS data exported into: $outdir"
+  echo "starting keyword search bootstrap (values, fields)"
+  das_bootstrap_kws
+  echo "bootstrap done"
 }
 
 # Verify the security string.
@@ -137,6 +205,22 @@ case ${1:-status} in
     status
     ;;
 
+  fetchmaps )
+    check "$2"
+    fetch_metadata
+    ;;
+
+  resetmaps )
+    check "$2"
+    reset_metadata
+    ;;
+
+  updatemaps )
+    check "$2"
+    stop
+    update_metadata
+    ;;
+
   stop )
     check "$2"
     stop
@@ -145,14 +229,10 @@ case ${1:-status} in
   help )
     perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
     ;;
-    
+
   bootstrap )
     bootstrap
-    ;;    
-    
-  kws_export_data )
-    kws_export_data
-    ;;     
+    ;;
 
   version )
     echo "$DAS_VERSION"
