Changes for DAS server splitting into DAS web and DAS cli servers

diff --git a/das/manage b/das/manage
--- a/das/manage
+++ b/das/manage
@@ -50,6 +50,7 @@ export X509_USER_CERT=$X509_USER_PROXY
 export X509_USER_KEY=$X509_USER_PROXY
 export STAGEDIR=$STATEDIR/stagingarea
 export DAS_CONFIG=$ROOT/config/$ME/das_cms.py
+export DAS_CONFIG_CLI=$ROOT/config/$ME/das_cms_cli.py
 mkdir -p $STAGEDIR
 
 cd $STATEDIR
@@ -93,6 +94,41 @@ sysboot()
   $dostart && start
 }
 
+# use global variable to assign DAS server status
+das_status="no"
+
+# helper function to check DAS server status
+check4das() {
+    das_cmd=`curl -s http://localhost:8212 | egrep -i "DAS systems" | grep -i "dbs"`
+    if  [ -n "$das_cmd" ]; then
+        das_status="ok"
+        return
+    fi
+    das_status="no"
+    return
+}
+
+# helper function to wait for DAS server to start
+# it will incrementally increase waiting time with 20 iterations (~3minute)
+wait4das() {
+    local counter=0
+    # check if mongodb is running
+    while [  $counter -lt 20 ]; do
+        check4das
+        if [ "$das_status" == "ok" ]; then
+            return
+        fi
+        let counter=counter+1
+        echo "DAS server is not running, check in $counter sec"
+        sleep $counter
+    done
+    check4das
+    if [ "$das_status" == "no" ]; then
+        echo "DAS is not running, unable to start DAS server"
+        exit 1
+    fi
+}
+
 start()
 {
   echo "starting $ME"
@@ -103,6 +139,10 @@ start()
   # start DAS service (it will load DAS maps into MongoDB and start DAS server)
   DASMAPS_DIR=$STAGEDIR $DAS_ROOT/bin/das_server start \
       </dev/null 2>&1 | rotatelogs $LOGDIR/das-%Y%m%d.log 86400 >/dev/null 2>&1 &
+  # wait until DAS service is up and running and then start second one to server CLI requests
+  wait4das
+  DASMAPS_DIR=$STAGEDIR $DAS_ROOT/bin/das_server start_cli \
+      </dev/null 2>&1 | rotatelogs $LOGDIR/das_cli-%Y%m%d.log 86400 >/dev/null 2>&1 &
 }
 
 # Stop the service.
